import { GrainsCrop } from '@/types/Grains/crop.input';
import { GrainsInput } from '@/types/Grains/input';
import { veg1, veg2, veg3, veg4 } from './vegetation.data';

export const grainWheat: GrainsCrop = {
  type: 'Wheat',
  state: 'nsw',
  productionSystem: 'Non-irrigated crop',
  averageGrainYield: 3,
  areaSown: 1000,
  nonUreaNitrogen: 2,
  ureaApplication: 50,
  ureaAmmoniumNitrate: 5,
  phosphorusApplication: 20,
  potassiumApplication: 0,
  sulfurApplication: 0,
  rainfallAbove600: true,
  fractionOfAnnualCropBurnt: 1,
  herbicideUse: 8.5,
  glyphosateOtherHerbicideUse: 3.6,
  electricityAllocation: 0.2,
  limestone: 500,
  limestoneFraction: 1,
  dieselUse: 200,
  petrolUse: 500,
  lpg: 100,
};

export const grainSorghum: GrainsCrop = {
  type: 'Sorghum',
  state: 'nsw',
  productionSystem: 'Non-irrigated crop',
  averageGrainYield: 2.5,
  areaSown: 200,
  nonUreaNitrogen: 0,
  ureaApplication: 40,
  ureaAmmoniumNitrate: 10,
  phosphorusApplication: 20,
  potassiumApplication: 0,
  sulfurApplication: 2,
  rainfallAbove600: false,
  fractionOfAnnualCropBurnt: 0.5,
  herbicideUse: 4.25,
  glyphosateOtherHerbicideUse: 10.8,
  electricityAllocation: 0.4,
  limestone: 100,
  limestoneFraction: 1,
  dieselUse: 500,
  petrolUse: 250,
  lpg: 110,
};

export const grainLegume: GrainsCrop = {
  type: 'Other legume',
  state: 'nsw',
  productionSystem: 'Irrigated crop',
  averageGrainYield: 2,
  areaSown: 500,
  nonUreaNitrogen: 0,
  ureaApplication: 20,
  ureaAmmoniumNitrate: 5,
  phosphorusApplication: 20,
  potassiumApplication: 0,
  sulfurApplication: 0,
  rainfallAbove600: false,
  fractionOfAnnualCropBurnt: 0,
  herbicideUse: 2.12,
  glyphosateOtherHerbicideUse: 3.6,
  electricityAllocation: 0.2,
  limestone: 250,
  limestoneFraction: 1,
  dieselUse: 600,
  petrolUse: 400,
  lpg: 120,
};

export const grainGrass: GrainsCrop = {
  type: 'Annual grass',
  state: 'nsw',
  productionSystem: 'Non-irrigated crop',
  averageGrainYield: 6,
  areaSown: 800,
  nonUreaNitrogen: 0,
  ureaApplication: 30,
  ureaAmmoniumNitrate: 12,
  phosphorusApplication: 20,
  potassiumApplication: 3,
  sulfurApplication: 0,
  rainfallAbove600: false,
  fractionOfAnnualCropBurnt: 0,
  herbicideUse: 4.25,
  glyphosateOtherHerbicideUse: 18,
  electricityAllocation: 0.1,
  limestone: 400,
  limestoneFraction: 1,
  dieselUse: 150,
  petrolUse: 100,
  lpg: 130,
};

export const grainTriticale: GrainsCrop = {
  type: 'Triticale',
  state: 'nsw',
  productionSystem: 'Non-irrigated crop',
  averageGrainYield: 4,
  areaSown: 300,
  nonUreaNitrogen: 0,
  ureaApplication: 50,
  ureaAmmoniumNitrate: 15,
  phosphorusApplication: 20,
  potassiumApplication: 4,
  sulfurApplication: 4,
  rainfallAbove600: false,
  fractionOfAnnualCropBurnt: 0,
  herbicideUse: 8.5,
  glyphosateOtherHerbicideUse: 5.4,
  electricityAllocation: 0.1,
  limestone: 150,
  limestoneFraction: 1,
  dieselUse: 50,
  petrolUse: 250,
  lpg: 140,
};

export const grainsTestData: GrainsInput = {
  crops: [grainWheat, grainSorghum, grainLegume, grainGrass, grainTriticale],
  electricityUse: 4000,
  electricityRenewable: 0,
  state: 'nsw',
  vegetation: [veg1, veg2, veg3, veg4],
};

export const grainsTestData102: GrainsInput = {
  state: 'nsw',
  electricityRenewable: 0,
  electricityUse: 2650,
  crops: [
    {
      type: 'Hops',
      state: 'nsw',
      productionSystem: 'Non-irrigated crop',
      averageGrainYield: 2.5,
      areaSown: 180,
      nonUreaNitrogen: 6.5,
      ureaApplication: 350,
      ureaAmmoniumNitrate: 100,
      phosphorusApplication: 19.515,
      potassiumApplication: 0,
      sulfurApplication: 6.6,
      rainfallAbove600: false,
      fractionOfAnnualCropBurnt: 0.1,
      herbicideUse: 54.504,
      glyphosateOtherHerbicideUse: 0,
      electricityAllocation: 1,
      limestone: 360,
      limestoneFraction: 0.5,
      dieselUse: 6352,
      petrolUse: 0,
      lpg: 100,
    },
  ],
  vegetation: [
    {
      vegetation: {
        region: 'Central Wheat Belt',
        treeSpecies: 'Mixed species (Environmental Plantings)',
        soil: 'Coloured Sands',
        area: 22,
        age: 7,
      },
      allocationToCrops: [1],
    },
  ],
};
