export enum CalculatorName {
  Beef = 'beef',
  Aquaculture = 'aquaculture',
  Buffalo = 'buffalo',
  Cotton = 'cotton',
  Dairy = 'dairy',
  Deer = 'deer',
  Feedlot = 'feedlot',
  Goat = 'goat',
  Grains = 'grains',
  Horticulture = 'horticulture',
  Pork = 'pork',
  Poultry = 'poultry',
  Processing = 'processing',
  Rice = 'rice',
  Sheep = 'sheep',
  SheepBeef = 'sheepbeef',
  Sugar = 'sugar',
  Vineyard = 'vineyard',
  WildCatchFishery = 'wildcatchfishery',
  WildSeaFisheries = 'wildseafisheries',
}
