# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_vineyard_request_vineyards_inner import PostVineyardRequestVineyardsInner

class TestPostVineyardRequestVineyardsInner(unittest.TestCase):
    """PostVineyardRequestVineyardsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostVineyardRequestVineyardsInner:
        """Test PostVineyardRequestVineyardsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostVineyardRequestVineyardsInner`
        """
        model = PostVineyardRequestVineyardsInner()
        if include_optional:
            return PostVineyardRequestVineyardsInner(
                id = '',
                state = 'nsw',
                rainfall_above600 = True,
                irrigated = True,
                area_planted = 1.337,
                average_yield = 1.337,
                non_urea_nitrogen = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                urea_application = 1.337,
                urea_ammonium_nitrate = 1.337,
                limestone = 1.337,
                limestone_fraction = 1.337,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                electricity_source = 'State Grid',
                fuel = {
                    'key' : null
                    },
                fluid_waste = [
                    {
                        'key' : null
                        }
                    ],
                solid_waste = {
                    'key' : null
                    },
                inbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                outbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                total_commercial_flights_km = 1.337
            )
        else:
            return PostVineyardRequestVineyardsInner(
                state = 'nsw',
                rainfall_above600 = True,
                irrigated = True,
                area_planted = 1.337,
                average_yield = 1.337,
                non_urea_nitrogen = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                urea_application = 1.337,
                urea_ammonium_nitrate = 1.337,
                limestone = 1.337,
                limestone_fraction = 1.337,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                electricity_source = 'State Grid',
                fuel = {
                    'key' : null
                    },
                fluid_waste = [
                    {
                        'key' : null
                        }
                    ],
                solid_waste = {
                    'key' : null
                    },
                inbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                outbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                total_commercial_flights_km = 1.337,
        )
        """

    def testPostVineyardRequestVineyardsInner(self):
        """Test PostVineyardRequestVineyardsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
