# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_buffalo_request_buffalos_inner import PostBuffaloRequestBuffalosInner

class TestPostBuffaloRequestBuffalosInner(unittest.TestCase):
    """PostBuffaloRequestBuffalosInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBuffaloRequestBuffalosInner:
        """Test PostBuffaloRequestBuffalosInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBuffaloRequestBuffalosInner`
        """
        model = PostBuffaloRequestBuffalosInner()
        if include_optional:
            return PostBuffaloRequestBuffalosInner(
                id = '',
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                cows_calving = {
                    'key' : null
                    },
                seasonal_calving = {
                    'key' : null
                    }
            )
        else:
            return PostBuffaloRequestBuffalosInner(
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                cows_calving = {
                    'key' : null
                    },
                seasonal_calving = {
                    'key' : null
                    },
        )
        """

    def testPostBuffaloRequestBuffalosInner(self):
        """Test PostBuffaloRequestBuffalosInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
