# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner_classes import PostDairyRequestDairyInnerClasses

class TestPostDairyRequestDairyInnerClasses(unittest.TestCase):
    """PostDairyRequestDairyInnerClasses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInnerClasses:
        """Test PostDairyRequestDairyInnerClasses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInnerClasses`
        """
        model = PostDairyRequestDairyInnerClasses()
        if include_optional:
            return PostDairyRequestDairyInnerClasses(
                milking_cows = {
                    'key' : null
                    },
                heifers_lt1 = {
                    'key' : null
                    },
                heifers_gt1 = {
                    'key' : null
                    },
                dairy_bulls_lt1 = {
                    'key' : null
                    },
                dairy_bulls_gt1 = {
                    'key' : null
                    }
            )
        else:
            return PostDairyRequestDairyInnerClasses(
                milking_cows = {
                    'key' : null
                    },
                heifers_lt1 = {
                    'key' : null
                    },
                heifers_gt1 = {
                    'key' : null
                    },
                dairy_bulls_lt1 = {
                    'key' : null
                    },
                dairy_bulls_gt1 = {
                    'key' : null
                    },
        )
        """

    def testPostDairyRequestDairyInnerClasses(self):
        """Test PostDairyRequestDairyInnerClasses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
