# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner_groups_inner_feed_inner_ingredients import PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients

class TestPostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients(unittest.TestCase):
    """PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients:
        """Test PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients`
        """
        model = PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients()
        if include_optional:
            return PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients(
                wheat = 1.337,
                barley = 1.337,
                sorghum = 1.337,
                soybean = 1.337,
                millrun = 1.337
            )
        else:
            return PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients(
        )
        """

    def testPostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients(self):
        """Test PostPoultryRequestBroilersInnerGroupsInnerFeedInnerIngredients"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
