# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sugar200_response_intermediate_inner import PostSugar200ResponseIntermediateInner

class TestPostSugar200ResponseIntermediateInner(unittest.TestCase):
    """PostSugar200ResponseIntermediateInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSugar200ResponseIntermediateInner:
        """Test PostSugar200ResponseIntermediateInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSugar200ResponseIntermediateInner`
        """
        model = PostSugar200ResponseIntermediateInner()
        if include_optional:
            return PostSugar200ResponseIntermediateInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = 1.337,
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    }
            )
        else:
            return PostSugar200ResponseIntermediateInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = 1.337,
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    },
        )
        """

    def testPostSugar200ResponseIntermediateInner(self):
        """Test PostSugar200ResponseIntermediateInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
