# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sheep_request_sheep_inner_classes import PostSheepRequestSheepInnerClasses

class TestPostSheepRequestSheepInnerClasses(unittest.TestCase):
    """PostSheepRequestSheepInnerClasses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSheepRequestSheepInnerClasses:
        """Test PostSheepRequestSheepInnerClasses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSheepRequestSheepInnerClasses`
        """
        model = PostSheepRequestSheepInnerClasses()
        if include_optional:
            return PostSheepRequestSheepInnerClasses(
                rams = {
                    'key' : null
                    },
                trade_rams = {
                    'key' : null
                    },
                wethers = {
                    'key' : null
                    },
                trade_wethers = {
                    'key' : null
                    },
                maiden_breeding_ewes = {
                    'key' : null
                    },
                trade_maiden_breeding_ewes = {
                    'key' : null
                    },
                breeding_ewes = {
                    'key' : null
                    },
                trade_breeding_ewes = {
                    'key' : null
                    },
                other_ewes = {
                    'key' : null
                    },
                trade_other_ewes = {
                    'key' : null
                    },
                ewe_lambs = {
                    'key' : null
                    },
                trade_ewe_lambs = {
                    'key' : null
                    },
                wether_lambs = {
                    'key' : null
                    },
                trade_wether_lambs = {
                    'key' : null
                    },
                trade_ewes = {
                    'key' : null
                    },
                trade_lambs_and_hoggets = {
                    'key' : null
                    }
            )
        else:
            return PostSheepRequestSheepInnerClasses(
                breeding_ewes = {
                    'key' : null
                    },
                ewe_lambs = {
                    'key' : null
                    },
                wether_lambs = {
                    'key' : null
                    },
        )
        """

    def testPostSheepRequestSheepInnerClasses(self):
        """Test PostSheepRequestSheepInnerClasses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
