# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_deer_request_deers_inner_seasonal_fawning import PostDeerRequestDeersInnerSeasonalFawning

class TestPostDeerRequestDeersInnerSeasonalFawning(unittest.TestCase):
    """PostDeerRequestDeersInnerSeasonalFawning unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDeerRequestDeersInnerSeasonalFawning:
        """Test PostDeerRequestDeersInnerSeasonalFawning
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDeerRequestDeersInnerSeasonalFawning`
        """
        model = PostDeerRequestDeersInnerSeasonalFawning()
        if include_optional:
            return PostDeerRequestDeersInnerSeasonalFawning(
                spring = 1.337,
                summer = 1.337,
                autumn = 1.337,
                winter = 1.337
            )
        else:
            return PostDeerRequestDeersInnerSeasonalFawning(
                spring = 1.337,
                summer = 1.337,
                autumn = 1.337,
                winter = 1.337,
        )
        """

    def testPostDeerRequestDeersInnerSeasonalFawning(self):
        """Test PostDeerRequestDeersInnerSeasonalFawning"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
