# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner_meat_chicken_layers_purchases import PostPoultryRequestBroilersInnerMeatChickenLayersPurchases

class TestPostPoultryRequestBroilersInnerMeatChickenLayersPurchases(unittest.TestCase):
    """PostPoultryRequestBroilersInnerMeatChickenLayersPurchases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInnerMeatChickenLayersPurchases:
        """Test PostPoultryRequestBroilersInnerMeatChickenLayersPurchases
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInnerMeatChickenLayersPurchases`
        """
        model = PostPoultryRequestBroilersInnerMeatChickenLayersPurchases()
        if include_optional:
            return PostPoultryRequestBroilersInnerMeatChickenLayersPurchases(
                head = 1.337,
                purchase_weight = 1.337
            )
        else:
            return PostPoultryRequestBroilersInnerMeatChickenLayersPurchases(
                head = 1.337,
                purchase_weight = 1.337,
        )
        """

    def testPostPoultryRequestBroilersInnerMeatChickenLayersPurchases(self):
        """Test PostPoultryRequestBroilersInnerMeatChickenLayersPurchases"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
