# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_beef_request import PostBeefRequest

class TestPostBeefRequest(unittest.TestCase):
    """PostBeefRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBeefRequest:
        """Test PostBeefRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBeefRequest`
        """
        model = PostBeefRequest()
        if include_optional:
            return PostBeefRequest(
                state = 'nsw',
                north_of_tropic_of_capricorn = True,
                rainfall_above600 = True,
                beef = [
                    {
                        'key' : null
                        }
                    ],
                burning = [
                    {
                        'key' : null
                        }
                    ],
                vegetation = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PostBeefRequest(
                state = 'nsw',
                north_of_tropic_of_capricorn = True,
                rainfall_above600 = True,
                beef = [
                    {
                        'key' : null
                        }
                    ],
                burning = [
                    {
                        'key' : null
                        }
                    ],
                vegetation = [
                    {
                        'key' : null
                        }
                    ],
        )
        """

    def testPostBeefRequest(self):
        """Test PostBeefRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
