# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy200_response_intensities import PostDairy200ResponseIntensities

class TestPostDairy200ResponseIntensities(unittest.TestCase):
    """PostDairy200ResponseIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairy200ResponseIntensities:
        """Test PostDairy200ResponseIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairy200ResponseIntensities`
        """
        model = PostDairy200ResponseIntensities()
        if include_optional:
            return PostDairy200ResponseIntensities(
                milk_solids_produced_tonnes = 1.337,
                intensity = 1.337
            )
        else:
            return PostDairy200ResponseIntensities(
                milk_solids_produced_tonnes = 1.337,
                intensity = 1.337,
        )
        """

    def testPostDairy200ResponseIntensities(self):
        """Test PostDairy200ResponseIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
