# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_goat_request_goats_inner_classes import PostGoatRequestGoatsInnerClasses

class TestPostGoatRequestGoatsInnerClasses(unittest.TestCase):
    """PostGoatRequestGoatsInnerClasses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostGoatRequestGoatsInnerClasses:
        """Test PostGoatRequestGoatsInnerClasses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostGoatRequestGoatsInnerClasses`
        """
        model = PostGoatRequestGoatsInnerClasses()
        if include_optional:
            return PostGoatRequestGoatsInnerClasses(
                bucks_billy = {
                    'key' : null
                    },
                trade_bucks = {
                    'key' : null
                    },
                wethers = {
                    'key' : null
                    },
                trade_wethers = {
                    'key' : null
                    },
                maiden_breeding_does_nannies = {
                    'key' : null
                    },
                trade_maiden_breeding_does_nannies = {
                    'key' : null
                    },
                breeding_does_nannies = {
                    'key' : null
                    },
                trade_breeding_does_nannies = {
                    'key' : null
                    },
                other_does_culled_females = {
                    'key' : null
                    },
                trade_other_does_culled_females = {
                    'key' : null
                    },
                kids = {
                    'key' : null
                    },
                trade_kids = {
                    'key' : null
                    },
                trade_does = {
                    'key' : null
                    }
            )
        else:
            return PostGoatRequestGoatsInnerClasses(
        )
        """

    def testPostGoatRequestGoatsInnerClasses(self):
        """Test PostGoatRequestGoatsInnerClasses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
