# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_processing200_response_intensities_inner import PostProcessing200ResponseIntensitiesInner

class TestPostProcessing200ResponseIntensitiesInner(unittest.TestCase):
    """PostProcessing200ResponseIntensitiesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostProcessing200ResponseIntensitiesInner:
        """Test PostProcessing200ResponseIntensitiesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostProcessing200ResponseIntensitiesInner`
        """
        model = PostProcessing200ResponseIntensitiesInner()
        if include_optional:
            return PostProcessing200ResponseIntensitiesInner(
                units_produced = 1.337,
                unit_of_product = 'litre',
                processing_excluding_carbon_offsets = 1.337,
                processing_including_carbon_offsets = 1.337
            )
        else:
            return PostProcessing200ResponseIntensitiesInner(
                units_produced = 1.337,
                unit_of_product = 'litre',
                processing_excluding_carbon_offsets = 1.337,
                processing_including_carbon_offsets = 1.337,
        )
        """

    def testPostProcessing200ResponseIntensitiesInner(self):
        """Test PostProcessing200ResponseIntensitiesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
