# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner import PostDairyRequestDairyInner

class TestPostDairyRequestDairyInner(unittest.TestCase):
    """PostDairyRequestDairyInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInner:
        """Test PostDairyRequestDairyInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInner`
        """
        model = PostDairyRequestDairyInner()
        if include_optional:
            return PostDairyRequestDairyInner(
                id = '',
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                seasonal_fertiliser = {
                    'key' : null
                    },
                areas = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                cottonseed_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_management_milking_cows = {
                    'key' : null
                    },
                manure_management_other_dairy_cows = {
                    'key' : null
                    },
                emissions_allocation_to_red_meat_production = 0,
                truck_type = '4 Deck Trailer',
                distance_cattle_transported = 1.337
            )
        else:
            return PostDairyRequestDairyInner(
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                seasonal_fertiliser = {
                    'key' : null
                    },
                areas = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                cottonseed_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_management_milking_cows = {
                    'key' : null
                    },
                manure_management_other_dairy_cows = {
                    'key' : null
                    },
                emissions_allocation_to_red_meat_production = 0,
                truck_type = '4 Deck Trailer',
                distance_cattle_transported = 1.337,
        )
        """

    def testPostDairyRequestDairyInner(self):
        """Test PostDairyRequestDairyInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
