# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sheep200_response_intermediate_inner_intensities import PostSheep200ResponseIntermediateInnerIntensities

class TestPostSheep200ResponseIntermediateInnerIntensities(unittest.TestCase):
    """PostSheep200ResponseIntermediateInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSheep200ResponseIntermediateInnerIntensities:
        """Test PostSheep200ResponseIntermediateInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSheep200ResponseIntermediateInnerIntensities`
        """
        model = PostSheep200ResponseIntermediateInnerIntensities()
        if include_optional:
            return PostSheep200ResponseIntermediateInnerIntensities(
                wool_produced_kg = 1.337,
                sheep_meat_produced_kg = 1.337,
                wool_including_sequestration = 1.337,
                wool_excluding_sequestration = 1.337,
                sheep_meat_breeding_including_sequestration = 1.337,
                sheep_meat_breeding_excluding_sequestration = 1.337
            )
        else:
            return PostSheep200ResponseIntermediateInnerIntensities(
                wool_produced_kg = 1.337,
                sheep_meat_produced_kg = 1.337,
                wool_including_sequestration = 1.337,
                wool_excluding_sequestration = 1.337,
                sheep_meat_breeding_including_sequestration = 1.337,
                sheep_meat_breeding_excluding_sequestration = 1.337,
        )
        """

    def testPostSheep200ResponseIntermediateInnerIntensities(self):
        """Test PostSheep200ResponseIntermediateInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
