# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_wildseafisheries_request_enterprises_inner import PostWildseafisheriesRequestEnterprisesInner

class TestPostWildseafisheriesRequestEnterprisesInner(unittest.TestCase):
    """PostWildseafisheriesRequestEnterprisesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWildseafisheriesRequestEnterprisesInner:
        """Test PostWildseafisheriesRequestEnterprisesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWildseafisheriesRequestEnterprisesInner`
        """
        model = PostWildseafisheriesRequestEnterprisesInner()
        if include_optional:
            return PostWildseafisheriesRequestEnterprisesInner(
                id = '',
                state = 'nsw',
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                total_whole_weight_caught = 1.337,
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                refrigerants = [
                    {
                        'key' : null
                        }
                    ],
                transports = [
                    {
                        'key' : null
                        }
                    ],
                flights = [
                    {
                        'key' : null
                        }
                    ],
                bait = [
                    {
                        'key' : null
                        }
                    ],
                custombait = [
                    {
                        'key' : null
                        }
                    ],
                carbon_offset = 1.337
            )
        else:
            return PostWildseafisheriesRequestEnterprisesInner(
                state = 'nsw',
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                total_whole_weight_caught = 1.337,
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                refrigerants = [
                    {
                        'key' : null
                        }
                    ],
                transports = [
                    {
                        'key' : null
                        }
                    ],
                flights = [
                    {
                        'key' : null
                        }
                    ],
                bait = [
                    {
                        'key' : null
                        }
                    ],
                custombait = [
                    {
                        'key' : null
                        }
                    ],
                carbon_offset = 1.337,
        )
        """

    def testPostWildseafisheriesRequestEnterprisesInner(self):
        """Test PostWildseafisheriesRequestEnterprisesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
