# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_layers_inner import PostPoultryRequestLayersInner

class TestPostPoultryRequestLayersInner(unittest.TestCase):
    """PostPoultryRequestLayersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestLayersInner:
        """Test PostPoultryRequestLayersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestLayersInner`
        """
        model = PostPoultryRequestLayersInner()
        if include_optional:
            return PostPoultryRequestLayersInner(
                id = '',
                layers = {
                    'key' : null
                    },
                meat_chicken_layers = {
                    'key' : null
                    },
                feed = [
                    {
                        'key' : null
                        }
                    ],
                purchased_free_range = 1.337,
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                hay = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_waste_allocation = 1.337,
                waste_handled_drylot_or_storage = 1.337,
                litter_recycled = 1.337,
                litter_recycle_frequency = 1.337,
                meat_chicken_layers_purchases = {
                    'key' : null
                    },
                layers_purchases = {
                    'key' : null
                    },
                custom_feed_purchased = 1.337,
                custom_feed_emission_intensity = 1.337,
                meat_chicken_layers_egg_sale = {
                    'key' : null
                    },
                layers_egg_sale = {
                    'key' : null
                    }
            )
        else:
            return PostPoultryRequestLayersInner(
                layers = {
                    'key' : null
                    },
                meat_chicken_layers = {
                    'key' : null
                    },
                feed = [
                    {
                        'key' : null
                        }
                    ],
                purchased_free_range = 1.337,
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                hay = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_waste_allocation = 1.337,
                waste_handled_drylot_or_storage = 1.337,
                litter_recycled = 1.337,
                litter_recycle_frequency = 1.337,
                meat_chicken_layers_purchases = {
                    'key' : null
                    },
                layers_purchases = {
                    'key' : null
                    },
                custom_feed_purchased = 1.337,
                custom_feed_emission_intensity = 1.337,
                meat_chicken_layers_egg_sale = {
                    'key' : null
                    },
                layers_egg_sale = {
                    'key' : null
                    },
        )
        """

    def testPostPoultryRequestLayersInner(self):
        """Test PostPoultryRequestLayersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
