# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sugar_request_crops_inner import PostSugarRequestCropsInner

class TestPostSugarRequestCropsInner(unittest.TestCase):
    """PostSugarRequestCropsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSugarRequestCropsInner:
        """Test PostSugarRequestCropsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSugarRequestCropsInner`
        """
        model = PostSugarRequestCropsInner()
        if include_optional:
            return PostSugarRequestCropsInner(
                id = '',
                state = 'nsw',
                production_system = 'Non-irrigated crop',
                average_cane_yield = 1.337,
                percent_milled_cane_yield = 1.337,
                area_sown = 1.337,
                non_urea_nitrogen = 1.337,
                urea_application = 1.337,
                urea_ammonium_nitrate = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                rainfall_above600 = True,
                fraction_of_annual_crop_burnt = 1.337,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_allocation = 1.337,
                limestone = 1.337,
                limestone_fraction = 1.337,
                diesel_use = 1.337,
                petrol_use = 1.337,
                lpg = 1.337
            )
        else:
            return PostSugarRequestCropsInner(
                state = 'nsw',
                production_system = 'Non-irrigated crop',
                average_cane_yield = 1.337,
                area_sown = 1.337,
                non_urea_nitrogen = 1.337,
                urea_application = 1.337,
                urea_ammonium_nitrate = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                rainfall_above600 = True,
                fraction_of_annual_crop_burnt = 1.337,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_allocation = 1.337,
                limestone = 1.337,
                limestone_fraction = 1.337,
                diesel_use = 1.337,
                petrol_use = 1.337,
                lpg = 1.337,
        )
        """

    def testPostSugarRequestCropsInner(self):
        """Test PostSugarRequestCropsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
