# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_beef_request_beef_inner_fertiliser_other_fertilisers_inner import PostBeefRequestBeefInnerFertiliserOtherFertilisersInner

class TestPostBeefRequestBeefInnerFertiliserOtherFertilisersInner(unittest.TestCase):
    """PostBeefRequestBeefInnerFertiliserOtherFertilisersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBeefRequestBeefInnerFertiliserOtherFertilisersInner:
        """Test PostBeefRequestBeefInnerFertiliserOtherFertilisersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBeefRequestBeefInnerFertiliserOtherFertilisersInner`
        """
        model = PostBeefRequestBeefInnerFertiliserOtherFertilisersInner()
        if include_optional:
            return PostBeefRequestBeefInnerFertiliserOtherFertilisersInner(
                other_type = 'Monoammonium phosphate (MAP)',
                other_dryland = 1.337,
                other_irrigated = 1.337
            )
        else:
            return PostBeefRequestBeefInnerFertiliserOtherFertilisersInner(
                other_type = 'Monoammonium phosphate (MAP)',
                other_dryland = 1.337,
                other_irrigated = 1.337,
        )
        """

    def testPostBeefRequestBeefInnerFertiliserOtherFertilisersInner(self):
        """Test PostBeefRequestBeefInnerFertiliserOtherFertilisersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
