# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_deer_request_deers_inner_classes_trade_other_does import PostDeerRequestDeersInnerClassesTradeOtherDoes

class TestPostDeerRequestDeersInnerClassesTradeOtherDoes(unittest.TestCase):
    """PostDeerRequestDeersInnerClassesTradeOtherDoes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDeerRequestDeersInnerClassesTradeOtherDoes:
        """Test PostDeerRequestDeersInnerClassesTradeOtherDoes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDeerRequestDeersInnerClassesTradeOtherDoes`
        """
        model = PostDeerRequestDeersInnerClassesTradeOtherDoes()
        if include_optional:
            return PostDeerRequestDeersInnerClassesTradeOtherDoes(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    },
                head_sold = 1.337,
                sale_weight = 1.337,
                purchases = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PostDeerRequestDeersInnerClassesTradeOtherDoes(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    },
                head_sold = 1.337,
                sale_weight = 1.337,
        )
        """

    def testPostDeerRequestDeersInnerClassesTradeOtherDoes(self):
        """Test PostDeerRequestDeersInnerClassesTradeOtherDoes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
