# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_beef_request_beef_inner_classes_cows_gt2 import PostBeefRequestBeefInnerClassesCowsGt2

class TestPostBeefRequestBeefInnerClassesCowsGt2(unittest.TestCase):
    """PostBeefRequestBeefInnerClassesCowsGt2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBeefRequestBeefInnerClassesCowsGt2:
        """Test PostBeefRequestBeefInnerClassesCowsGt2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBeefRequestBeefInnerClassesCowsGt2`
        """
        model = PostBeefRequestBeefInnerClassesCowsGt2()
        if include_optional:
            return PostBeefRequestBeefInnerClassesCowsGt2(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    },
                head_purchased = 1.337,
                purchased_weight = 1.337,
                source = 'Dairy origin',
                head_sold = 1.337,
                sale_weight = 1.337,
                purchases = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PostBeefRequestBeefInnerClassesCowsGt2(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    },
                head_sold = 1.337,
                sale_weight = 1.337,
        )
        """

    def testPostBeefRequestBeefInnerClassesCowsGt2(self):
        """Test PostBeefRequestBeefInnerClassesCowsGt2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
