# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner_classes_milking_cows import PostDairyRequestDairyInnerClassesMilkingCows

class TestPostDairyRequestDairyInnerClassesMilkingCows(unittest.TestCase):
    """PostDairyRequestDairyInnerClassesMilkingCows unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInnerClassesMilkingCows:
        """Test PostDairyRequestDairyInnerClassesMilkingCows
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInnerClassesMilkingCows`
        """
        model = PostDairyRequestDairyInnerClassesMilkingCows()
        if include_optional:
            return PostDairyRequestDairyInnerClassesMilkingCows(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    }
            )
        else:
            return PostDairyRequestDairyInnerClassesMilkingCows(
                autumn = {
                    'key' : null
                    },
                winter = {
                    'key' : null
                    },
                spring = {
                    'key' : null
                    },
                summer = {
                    'key' : null
                    },
        )
        """

    def testPostDairyRequestDairyInnerClassesMilkingCows(self):
        """Test PostDairyRequestDairyInnerClassesMilkingCows"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
