# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_cotton200_response_intermediate_inner_intensities import PostCotton200ResponseIntermediateInnerIntensities

class TestPostCotton200ResponseIntermediateInnerIntensities(unittest.TestCase):
    """PostCotton200ResponseIntermediateInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostCotton200ResponseIntermediateInnerIntensities:
        """Test PostCotton200ResponseIntermediateInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostCotton200ResponseIntermediateInnerIntensities`
        """
        model = PostCotton200ResponseIntermediateInnerIntensities()
        if include_optional:
            return PostCotton200ResponseIntermediateInnerIntensities(
                cotton_yield_produced_tonnes = 1.337,
                bales_produced = 1.337,
                lint_produced_tonnes = 1.337,
                seed_produced_tonnes = 1.337,
                tonnes_crop_excluding_sequestration = 1.337,
                tonnes_crop_including_sequestration = 1.337,
                bales_excluding_sequestration = 1.337,
                bales_including_sequestration = 1.337,
                lint_including_sequestration = 1.337,
                lint_excluding_sequestration = 1.337,
                seed_including_sequestration = 1.337,
                seed_excluding_sequestration = 1.337,
                lint_economic_allocation = 1.337,
                seed_economic_allocation = 1.337
            )
        else:
            return PostCotton200ResponseIntermediateInnerIntensities(
                cotton_yield_produced_tonnes = 1.337,
                bales_produced = 1.337,
                lint_produced_tonnes = 1.337,
                seed_produced_tonnes = 1.337,
                tonnes_crop_excluding_sequestration = 1.337,
                tonnes_crop_including_sequestration = 1.337,
                bales_excluding_sequestration = 1.337,
                bales_including_sequestration = 1.337,
                lint_including_sequestration = 1.337,
                lint_excluding_sequestration = 1.337,
                seed_including_sequestration = 1.337,
                seed_excluding_sequestration = 1.337,
                lint_economic_allocation = 1.337,
                seed_economic_allocation = 1.337,
        )
        """

    def testPostCotton200ResponseIntermediateInnerIntensities(self):
        """Test PostCotton200ResponseIntermediateInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
