# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner_groups_inner_feed_inner import PostPoultryRequestBroilersInnerGroupsInnerFeedInner

class TestPostPoultryRequestBroilersInnerGroupsInnerFeedInner(unittest.TestCase):
    """PostPoultryRequestBroilersInnerGroupsInnerFeedInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInnerGroupsInnerFeedInner:
        """Test PostPoultryRequestBroilersInnerGroupsInnerFeedInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInnerGroupsInnerFeedInner`
        """
        model = PostPoultryRequestBroilersInnerGroupsInnerFeedInner()
        if include_optional:
            return PostPoultryRequestBroilersInnerGroupsInnerFeedInner(
                ingredients = {
                    'key' : null
                    },
                feed_purchased = 1.337,
                additional_ingredient = 1.337,
                emission_intensity = 1.337
            )
        else:
            return PostPoultryRequestBroilersInnerGroupsInnerFeedInner(
                ingredients = {
                    'key' : null
                    },
                feed_purchased = 1.337,
                additional_ingredient = 1.337,
                emission_intensity = 1.337,
        )
        """

    def testPostPoultryRequestBroilersInnerGroupsInnerFeedInner(self):
        """Test PostPoultryRequestBroilersInnerGroupsInnerFeedInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
