# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sheep_request_sheep_inner import PostSheepRequestSheepInner

class TestPostSheepRequestSheepInner(unittest.TestCase):
    """PostSheepRequestSheepInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSheepRequestSheepInner:
        """Test PostSheepRequestSheepInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSheepRequestSheepInner`
        """
        model = PostSheepRequestSheepInner()
        if include_optional:
            return PostSheepRequestSheepInner(
                id = '',
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                mineral_supplementation = {
                    'key' : null
                    },
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                merino_percent = 1.337,
                ewes_lambing = {
                    'key' : null
                    },
                seasonal_lambing = {
                    'key' : null
                    }
            )
        else:
            return PostSheepRequestSheepInner(
                classes = {
                    'key' : null
                    },
                limestone = 1.337,
                limestone_fraction = 1.337,
                fertiliser = {
                    'key' : null
                    },
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                mineral_supplementation = {
                    'key' : null
                    },
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                grain_feed = 1.337,
                hay_feed = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                merino_percent = 1.337,
                ewes_lambing = {
                    'key' : null
                    },
                seasonal_lambing = {
                    'key' : null
                    },
        )
        """

    def testPostSheepRequestSheepInner(self):
        """Test PostSheepRequestSheepInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
