# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_vineyard200_response_scope3 import PostVineyard200ResponseScope3

class TestPostVineyard200ResponseScope3(unittest.TestCase):
    """PostVineyard200ResponseScope3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostVineyard200ResponseScope3:
        """Test PostVineyard200ResponseScope3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostVineyard200ResponseScope3`
        """
        model = PostVineyard200ResponseScope3()
        if include_optional:
            return PostVineyard200ResponseScope3(
                fertiliser = 1.337,
                herbicide = 1.337,
                electricity = 1.337,
                fuel = 1.337,
                lime = 1.337,
                commercial_flights = 1.337,
                inbound_freight = 1.337,
                solid_waste_sent_offsite = 1.337,
                outbound_freight = 1.337,
                total = 1.337
            )
        else:
            return PostVineyard200ResponseScope3(
                fertiliser = 1.337,
                herbicide = 1.337,
                electricity = 1.337,
                fuel = 1.337,
                lime = 1.337,
                commercial_flights = 1.337,
                inbound_freight = 1.337,
                solid_waste_sent_offsite = 1.337,
                outbound_freight = 1.337,
                total = 1.337,
        )
        """

    def testPostVineyard200ResponseScope3(self):
        """Test PostVineyard200ResponseScope3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
