# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_aquaculture200_response_intensities import PostAquaculture200ResponseIntensities

class TestPostAquaculture200ResponseIntensities(unittest.TestCase):
    """PostAquaculture200ResponseIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAquaculture200ResponseIntensities:
        """Test PostAquaculture200ResponseIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAquaculture200ResponseIntensities`
        """
        model = PostAquaculture200ResponseIntensities()
        if include_optional:
            return PostAquaculture200ResponseIntensities(
                total_harvest_weight_kg = 1.337,
                aquaculture_excluding_carbon_offsets = 1.337,
                aquaculture_including_carbon_offsets = 1.337
            )
        else:
            return PostAquaculture200ResponseIntensities(
                total_harvest_weight_kg = 1.337,
                aquaculture_excluding_carbon_offsets = 1.337,
                aquaculture_including_carbon_offsets = 1.337,
        )
        """

    def testPostAquaculture200ResponseIntensities(self):
        """Test PostAquaculture200ResponseIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
