# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_beef_request_beef_inner_mineral_supplementation import PostBeefRequestBeefInnerMineralSupplementation

class TestPostBeefRequestBeefInnerMineralSupplementation(unittest.TestCase):
    """PostBeefRequestBeefInnerMineralSupplementation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBeefRequestBeefInnerMineralSupplementation:
        """Test PostBeefRequestBeefInnerMineralSupplementation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBeefRequestBeefInnerMineralSupplementation`
        """
        model = PostBeefRequestBeefInnerMineralSupplementation()
        if include_optional:
            return PostBeefRequestBeefInnerMineralSupplementation(
                mineral_block = 1.337,
                mineral_block_urea = 1.337,
                weaner_block = 1.337,
                weaner_block_urea = 1.337,
                dry_season_mix = 1.337,
                dry_season_mix_urea = 1.337
            )
        else:
            return PostBeefRequestBeefInnerMineralSupplementation(
                mineral_block = 1.337,
                mineral_block_urea = 1.337,
                weaner_block = 1.337,
                weaner_block_urea = 1.337,
                dry_season_mix = 1.337,
                dry_season_mix_urea = 1.337,
        )
        """

    def testPostBeefRequestBeefInnerMineralSupplementation(self):
        """Test PostBeefRequestBeefInnerMineralSupplementation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
