# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner import PostPoultryRequestBroilersInner

class TestPostPoultryRequestBroilersInner(unittest.TestCase):
    """PostPoultryRequestBroilersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInner:
        """Test PostPoultryRequestBroilersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInner`
        """
        model = PostPoultryRequestBroilersInner()
        if include_optional:
            return PostPoultryRequestBroilersInner(
                id = '',
                groups = [
                    {
                        'key' : null
                        }
                    ],
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                hay = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_waste_allocation = 1.337,
                waste_handled_drylot_or_storage = 1.337,
                litter_recycled = 1.337,
                litter_recycle_frequency = 1.337,
                purchased_free_range = 1.337,
                meat_chicken_growers_purchases = {
                    'key' : null
                    },
                meat_chicken_layers_purchases = {
                    'key' : null
                    },
                meat_other_purchases = {
                    'key' : null
                    },
                sales = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PostPoultryRequestBroilersInner(
                groups = [
                    {
                        'key' : null
                        }
                    ],
                diesel = 1.337,
                petrol = 1.337,
                lpg = 1.337,
                electricity_source = 'State Grid',
                electricity_renewable = 0,
                electricity_use = 1.337,
                hay = 1.337,
                herbicide = 1.337,
                herbicide_other = 1.337,
                manure_waste_allocation = 1.337,
                waste_handled_drylot_or_storage = 1.337,
                litter_recycled = 1.337,
                litter_recycle_frequency = 1.337,
                purchased_free_range = 1.337,
                meat_chicken_growers_purchases = {
                    'key' : null
                    },
                meat_chicken_layers_purchases = {
                    'key' : null
                    },
                meat_other_purchases = {
                    'key' : null
                    },
                sales = [
                    {
                        'key' : null
                        }
                    ],
        )
        """

    def testPostPoultryRequestBroilersInner(self):
        """Test PostPoultryRequestBroilersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
