# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_horticulture200_response_intermediate_inner_intensities_with_sequestration import PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration

class TestPostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration(unittest.TestCase):
    """PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration:
        """Test PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration`
        """
        model = PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration()
        if include_optional:
            return PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration(
                crop_produced_tonnes = 1.337,
                tonnes_crop_excluding_sequestration = 1.337,
                tonnes_crop_including_sequestration = 1.337
            )
        else:
            return PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration(
                crop_produced_tonnes = 1.337,
                tonnes_crop_excluding_sequestration = 1.337,
                tonnes_crop_including_sequestration = 1.337,
        )
        """

    def testPostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration(self):
        """Test PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
