# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sheep200_response import PostSheep200Response

class TestPostSheep200Response(unittest.TestCase):
    """PostSheep200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSheep200Response:
        """Test PostSheep200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSheep200Response`
        """
        model = PostSheep200Response()
        if include_optional:
            return PostSheep200Response(
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intermediate = [
                    {
                        'key' : null
                        }
                    ],
                net = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    }
            )
        else:
            return PostSheep200Response(
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intermediate = [
                    {
                        'key' : null
                        }
                    ],
                net = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
        )
        """

    def testPostSheep200Response(self):
        """Test PostSheep200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
