# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_pork_request_pork_inner_feed_products_inner_ingredients import PostPorkRequestPorkInnerFeedProductsInnerIngredients

class TestPostPorkRequestPorkInnerFeedProductsInnerIngredients(unittest.TestCase):
    """PostPorkRequestPorkInnerFeedProductsInnerIngredients unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPorkRequestPorkInnerFeedProductsInnerIngredients:
        """Test PostPorkRequestPorkInnerFeedProductsInnerIngredients
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPorkRequestPorkInnerFeedProductsInnerIngredients`
        """
        model = PostPorkRequestPorkInnerFeedProductsInnerIngredients()
        if include_optional:
            return PostPorkRequestPorkInnerFeedProductsInnerIngredients(
                wheat = 0,
                barley = 0,
                whey_powder = 0,
                canola_meal = 0,
                soybean_meal = 0,
                meat_meal = 0,
                blood_meal = 0,
                fishmeal = 0,
                tallow = 0,
                wheat_bran = 0,
                beet_pulp = 0,
                mill_mix = 0
            )
        else:
            return PostPorkRequestPorkInnerFeedProductsInnerIngredients(
        )
        """

    def testPostPorkRequestPorkInnerFeedProductsInnerIngredients(self):
        """Test PostPorkRequestPorkInnerFeedProductsInnerIngredients"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
