# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_aquaculture200_response_carbon_sequestration import PostAquaculture200ResponseCarbonSequestration

class TestPostAquaculture200ResponseCarbonSequestration(unittest.TestCase):
    """PostAquaculture200ResponseCarbonSequestration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAquaculture200ResponseCarbonSequestration:
        """Test PostAquaculture200ResponseCarbonSequestration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAquaculture200ResponseCarbonSequestration`
        """
        model = PostAquaculture200ResponseCarbonSequestration()
        if include_optional:
            return PostAquaculture200ResponseCarbonSequestration(
                total = 1.337,
                intermediate = [
                    1.337
                    ]
            )
        else:
            return PostAquaculture200ResponseCarbonSequestration(
                total = 1.337,
                intermediate = [
                    1.337
                    ],
        )
        """

    def testPostAquaculture200ResponseCarbonSequestration(self):
        """Test PostAquaculture200ResponseCarbonSequestration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
