# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_rice200_response_intensities import PostRice200ResponseIntensities

class TestPostRice200ResponseIntensities(unittest.TestCase):
    """PostRice200ResponseIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostRice200ResponseIntensities:
        """Test PostRice200ResponseIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostRice200ResponseIntensities`
        """
        model = PostRice200ResponseIntensities()
        if include_optional:
            return PostRice200ResponseIntensities(
                rice_produced_tonnes = 1.337,
                rice_excluding_sequestration = 1.337,
                rice_including_sequestration = 1.337,
                intensity = 1.337
            )
        else:
            return PostRice200ResponseIntensities(
                rice_produced_tonnes = 1.337,
                rice_excluding_sequestration = 1.337,
                rice_including_sequestration = 1.337,
                intensity = 1.337,
        )
        """

    def testPostRice200ResponseIntensities(self):
        """Test PostRice200ResponseIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
