# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_vineyard200_response_scope1 import PostVineyard200ResponseScope1

class TestPostVineyard200ResponseScope1(unittest.TestCase):
    """PostVineyard200ResponseScope1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostVineyard200ResponseScope1:
        """Test PostVineyard200ResponseScope1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostVineyard200ResponseScope1`
        """
        model = PostVineyard200ResponseScope1()
        if include_optional:
            return PostVineyard200ResponseScope1(
                fuel_co2 = 1.337,
                lime_co2 = 1.337,
                urea_co2 = 1.337,
                waste_water_co2 = 1.337,
                composted_solid_waste_co2 = 1.337,
                fuel_ch4 = 1.337,
                fertiliser_n2_o = 1.337,
                atmospheric_deposition_n2_o = 1.337,
                crop_residue_n2_o = 1.337,
                leaching_and_runoff_n2_o = 1.337,
                fuel_n2_o = 1.337,
                total_co2 = 1.337,
                total_ch4 = 1.337,
                total_n2_o = 1.337,
                total = 1.337
            )
        else:
            return PostVineyard200ResponseScope1(
                fuel_co2 = 1.337,
                lime_co2 = 1.337,
                urea_co2 = 1.337,
                waste_water_co2 = 1.337,
                composted_solid_waste_co2 = 1.337,
                fuel_ch4 = 1.337,
                fertiliser_n2_o = 1.337,
                atmospheric_deposition_n2_o = 1.337,
                crop_residue_n2_o = 1.337,
                leaching_and_runoff_n2_o = 1.337,
                fuel_n2_o = 1.337,
                total_co2 = 1.337,
                total_ch4 = 1.337,
                total_n2_o = 1.337,
                total = 1.337,
        )
        """

    def testPostVineyard200ResponseScope1(self):
        """Test PostVineyard200ResponseScope1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
