# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_deer200_response_intensities import PostDeer200ResponseIntensities

class TestPostDeer200ResponseIntensities(unittest.TestCase):
    """PostDeer200ResponseIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDeer200ResponseIntensities:
        """Test PostDeer200ResponseIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDeer200ResponseIntensities`
        """
        model = PostDeer200ResponseIntensities()
        if include_optional:
            return PostDeer200ResponseIntensities(
                liveweight_produced_kg = 1.337,
                deer_meat_excluding_sequestration = 1.337,
                deer_meat_including_sequestration = 1.337
            )
        else:
            return PostDeer200ResponseIntensities(
                liveweight_produced_kg = 1.337,
                deer_meat_excluding_sequestration = 1.337,
                deer_meat_including_sequestration = 1.337,
        )
        """

    def testPostDeer200ResponseIntensities(self):
        """Test PostDeer200ResponseIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
