# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_intermediate_broilers_inner_intensities import PostPoultry200ResponseIntermediateBroilersInnerIntensities

class TestPostPoultry200ResponseIntermediateBroilersInnerIntensities(unittest.TestCase):
    """PostPoultry200ResponseIntermediateBroilersInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseIntermediateBroilersInnerIntensities:
        """Test PostPoultry200ResponseIntermediateBroilersInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseIntermediateBroilersInnerIntensities`
        """
        model = PostPoultry200ResponseIntermediateBroilersInnerIntensities()
        if include_optional:
            return PostPoultry200ResponseIntermediateBroilersInnerIntensities(
                poultry_meat_including_sequestration = 1.337,
                poultry_meat_excluding_sequestration = 1.337,
                meat_produced_kg = 1.337
            )
        else:
            return PostPoultry200ResponseIntermediateBroilersInnerIntensities(
                poultry_meat_including_sequestration = 1.337,
                poultry_meat_excluding_sequestration = 1.337,
                meat_produced_kg = 1.337,
        )
        """

    def testPostPoultry200ResponseIntermediateBroilersInnerIntensities(self):
        """Test PostPoultry200ResponseIntermediateBroilersInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
