# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_feedlot200_response_scope3 import PostFeedlot200ResponseScope3

class TestPostFeedlot200ResponseScope3(unittest.TestCase):
    """PostFeedlot200ResponseScope3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostFeedlot200ResponseScope3:
        """Test PostFeedlot200ResponseScope3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostFeedlot200ResponseScope3`
        """
        model = PostFeedlot200ResponseScope3()
        if include_optional:
            return PostFeedlot200ResponseScope3(
                fertiliser = 1.337,
                herbicide = 1.337,
                electricity = 1.337,
                fuel = 1.337,
                lime = 1.337,
                feed = 1.337,
                purchase_livestock = 1.337,
                total = 1.337
            )
        else:
            return PostFeedlot200ResponseScope3(
                fertiliser = 1.337,
                herbicide = 1.337,
                electricity = 1.337,
                fuel = 1.337,
                lime = 1.337,
                feed = 1.337,
                purchase_livestock = 1.337,
                total = 1.337,
        )
        """

    def testPostFeedlot200ResponseScope3(self):
        """Test PostFeedlot200ResponseScope3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
