# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_feedlot_request_feedlots_inner_purchases_bulls_gt1_inner import PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner

class TestPostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner(unittest.TestCase):
    """PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner:
        """Test PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner`
        """
        model = PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner()
        if include_optional:
            return PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner(
                head = 1.337,
                purchase_weight = 1.337,
                purchase_source = 'sth NSW/VIC/sth SA'
            )
        else:
            return PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner(
                head = 1.337,
                purchase_weight = 1.337,
                purchase_source = 'sth NSW/VIC/sth SA',
        )
        """

    def testPostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner(self):
        """Test PostFeedlotRequestFeedlotsInnerPurchasesBullsGt1Inner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
