# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_net import PostPoultry200ResponseNet

class TestPostPoultry200ResponseNet(unittest.TestCase):
    """PostPoultry200ResponseNet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseNet:
        """Test PostPoultry200ResponseNet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseNet`
        """
        model = PostPoultry200ResponseNet()
        if include_optional:
            return PostPoultry200ResponseNet(
                total = 1.337,
                broilers = 1.337,
                layers = 1.337
            )
        else:
            return PostPoultry200ResponseNet(
                total = 1.337,
                broilers = 1.337,
                layers = 1.337,
        )
        """

    def testPostPoultry200ResponseNet(self):
        """Test PostPoultry200ResponseNet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
