# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_intermediate_layers_inner_intensities import PostPoultry200ResponseIntermediateLayersInnerIntensities

class TestPostPoultry200ResponseIntermediateLayersInnerIntensities(unittest.TestCase):
    """PostPoultry200ResponseIntermediateLayersInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseIntermediateLayersInnerIntensities:
        """Test PostPoultry200ResponseIntermediateLayersInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseIntermediateLayersInnerIntensities`
        """
        model = PostPoultry200ResponseIntermediateLayersInnerIntensities()
        if include_optional:
            return PostPoultry200ResponseIntermediateLayersInnerIntensities(
                poultry_eggs_including_sequestration = 1.337,
                poultry_eggs_excluding_sequestration = 1.337,
                eggs_produced_kg = 1.337
            )
        else:
            return PostPoultry200ResponseIntermediateLayersInnerIntensities(
                poultry_eggs_including_sequestration = 1.337,
                poultry_eggs_excluding_sequestration = 1.337,
                eggs_produced_kg = 1.337,
        )
        """

    def testPostPoultry200ResponseIntermediateLayersInnerIntensities(self):
        """Test PostPoultry200ResponseIntermediateLayersInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
