# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_wildcatchfishery_request_enterprises_inner import PostWildcatchfisheryRequestEnterprisesInner

class TestPostWildcatchfisheryRequestEnterprisesInner(unittest.TestCase):
    """PostWildcatchfisheryRequestEnterprisesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWildcatchfisheryRequestEnterprisesInner:
        """Test PostWildcatchfisheryRequestEnterprisesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWildcatchfisheryRequestEnterprisesInner`
        """
        model = PostWildcatchfisheryRequestEnterprisesInner()
        if include_optional:
            return PostWildcatchfisheryRequestEnterprisesInner(
                id = '',
                state = 'nsw',
                production_system = 'Abalone',
                total_harvest_kg = 1.337,
                refrigerants = [
                    openapi_client.models.post_horticulture_request_crops_inner_refrigerants_inner.post_horticulture_request_crops_inner_refrigerants_inner(
                        refrigerant = 'HFC-23', 
                        charge_size = 1.337, )
                    ],
                bait = [
                    {
                        'key' : null
                        }
                    ],
                custom_bait = [
                    {
                        'key' : null
                        }
                    ],
                inbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                outbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                total_commercial_flights_km = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                electricity_source = 'State Grid',
                fuel = {
                    'key' : null
                    },
                fluid_waste = [
                    {
                        'key' : null
                        }
                    ],
                solid_waste = {
                    'key' : null
                    },
                carbon_offsets = 1.337
            )
        else:
            return PostWildcatchfisheryRequestEnterprisesInner(
                state = 'nsw',
                production_system = 'Abalone',
                total_harvest_kg = 1.337,
                refrigerants = [
                    openapi_client.models.post_horticulture_request_crops_inner_refrigerants_inner.post_horticulture_request_crops_inner_refrigerants_inner(
                        refrigerant = 'HFC-23', 
                        charge_size = 1.337, )
                    ],
                bait = [
                    {
                        'key' : null
                        }
                    ],
                custom_bait = [
                    {
                        'key' : null
                        }
                    ],
                inbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                outbound_freight = [
                    {
                        'key' : null
                        }
                    ],
                total_commercial_flights_km = 1.337,
                electricity_renewable = 0,
                electricity_use = 1.337,
                electricity_source = 'State Grid',
                fuel = {
                    'key' : null
                    },
                fluid_waste = [
                    {
                        'key' : null
                        }
                    ],
                solid_waste = {
                    'key' : null
                    },
        )
        """

    def testPostWildcatchfisheryRequestEnterprisesInner(self):
        """Test PostWildcatchfisheryRequestEnterprisesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
