# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sugar200_response_intermediate_inner_intensities import PostSugar200ResponseIntermediateInnerIntensities

class TestPostSugar200ResponseIntermediateInnerIntensities(unittest.TestCase):
    """PostSugar200ResponseIntermediateInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSugar200ResponseIntermediateInnerIntensities:
        """Test PostSugar200ResponseIntermediateInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSugar200ResponseIntermediateInnerIntensities`
        """
        model = PostSugar200ResponseIntermediateInnerIntensities()
        if include_optional:
            return PostSugar200ResponseIntermediateInnerIntensities(
                sugar_excluding_sequestration = 1.337,
                sugar_including_sequestration = 1.337,
                sugar_produced_kg = 1.337
            )
        else:
            return PostSugar200ResponseIntermediateInnerIntensities(
                sugar_excluding_sequestration = 1.337,
                sugar_including_sequestration = 1.337,
                sugar_produced_kg = 1.337,
        )
        """

    def testPostSugar200ResponseIntermediateInnerIntensities(self):
        """Test PostSugar200ResponseIntermediateInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
