# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_pork_request_pork_inner_classes_sows_manure_spring import PostPorkRequestPorkInnerClassesSowsManureSpring

class TestPostPorkRequestPorkInnerClassesSowsManureSpring(unittest.TestCase):
    """PostPorkRequestPorkInnerClassesSowsManureSpring unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPorkRequestPorkInnerClassesSowsManureSpring:
        """Test PostPorkRequestPorkInnerClassesSowsManureSpring
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPorkRequestPorkInnerClassesSowsManureSpring`
        """
        model = PostPorkRequestPorkInnerClassesSowsManureSpring()
        if include_optional:
            return PostPorkRequestPorkInnerClassesSowsManureSpring(
                outdoor_systems = 1.337,
                covered_anaerobic_pond = 1.337,
                uncovered_anaerobic_pond = 1.337,
                deep_litter = 1.337,
                undefined_system = 1.337
            )
        else:
            return PostPorkRequestPorkInnerClassesSowsManureSpring(
        )
        """

    def testPostPorkRequestPorkInnerClassesSowsManureSpring(self):
        """Test PostPorkRequestPorkInnerClassesSowsManureSpring"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
