# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner_sales_inner import PostPoultryRequestBroilersInnerSalesInner

class TestPostPoultryRequestBroilersInnerSalesInner(unittest.TestCase):
    """PostPoultryRequestBroilersInnerSalesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInnerSalesInner:
        """Test PostPoultryRequestBroilersInnerSalesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInnerSalesInner`
        """
        model = PostPoultryRequestBroilersInnerSalesInner()
        if include_optional:
            return PostPoultryRequestBroilersInnerSalesInner(
                meat_chicken_growers_sales = {
                    'key' : null
                    },
                meat_chicken_layers = {
                    'key' : null
                    },
                meat_other = {
                    'key' : null
                    }
            )
        else:
            return PostPoultryRequestBroilersInnerSalesInner(
                meat_chicken_growers_sales = {
                    'key' : null
                    },
                meat_chicken_layers = {
                    'key' : null
                    },
                meat_other = {
                    'key' : null
                    },
        )
        """

    def testPostPoultryRequestBroilersInnerSalesInner(self):
        """Test PostPoultryRequestBroilersInnerSalesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
