# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_rice_request_crops_inner import PostRiceRequestCropsInner

class TestPostRiceRequestCropsInner(unittest.TestCase):
    """PostRiceRequestCropsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostRiceRequestCropsInner:
        """Test PostRiceRequestCropsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostRiceRequestCropsInner`
        """
        model = PostRiceRequestCropsInner()
        if include_optional:
            return PostRiceRequestCropsInner(
                id = '',
                state = 'nsw',
                average_rice_yield = 1.337,
                area_sown = 1.337,
                growing_season_days = 1.337,
                water_regime_type = 'Upland',
                water_regime_sub_type = 'Continuously flooded',
                rice_preseason_flooding_period = 'Non flooded pre-season < 180 days',
                urea_application = 1.337,
                non_urea_nitrogen = 1.337,
                urea_ammonium_nitrate = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                fraction_of_annual_crop_burnt = 0,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_allocation = 0,
                limestone = 1.337,
                limestone_fraction = 1.337,
                diesel_use = 1.337,
                petrol_use = 1.337,
                lpg = 1.337
            )
        else:
            return PostRiceRequestCropsInner(
                state = 'nsw',
                average_rice_yield = 1.337,
                area_sown = 1.337,
                growing_season_days = 1.337,
                water_regime_type = 'Upland',
                water_regime_sub_type = 'Continuously flooded',
                rice_preseason_flooding_period = 'Non flooded pre-season < 180 days',
                urea_application = 1.337,
                non_urea_nitrogen = 1.337,
                urea_ammonium_nitrate = 1.337,
                phosphorus_application = 1.337,
                potassium_application = 1.337,
                sulfur_application = 1.337,
                fraction_of_annual_crop_burnt = 0,
                herbicide_use = 1.337,
                glyphosate_other_herbicide_use = 1.337,
                electricity_allocation = 0,
                limestone = 1.337,
                limestone_fraction = 1.337,
                diesel_use = 1.337,
                petrol_use = 1.337,
                lpg = 1.337,
        )
        """

    def testPostRiceRequestCropsInner(self):
        """Test PostRiceRequestCropsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
