# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_feedlot200_response_intermediate_inner_intensities import PostFeedlot200ResponseIntermediateInnerIntensities

class TestPostFeedlot200ResponseIntermediateInnerIntensities(unittest.TestCase):
    """PostFeedlot200ResponseIntermediateInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostFeedlot200ResponseIntermediateInnerIntensities:
        """Test PostFeedlot200ResponseIntermediateInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostFeedlot200ResponseIntermediateInnerIntensities`
        """
        model = PostFeedlot200ResponseIntermediateInnerIntensities()
        if include_optional:
            return PostFeedlot200ResponseIntermediateInnerIntensities(
                liveweight_produced_kg = 1.337,
                beef_including_sequestration = 1.337,
                beef_excluding_sequestration = 1.337
            )
        else:
            return PostFeedlot200ResponseIntermediateInnerIntensities(
                liveweight_produced_kg = 1.337,
                beef_including_sequestration = 1.337,
                beef_excluding_sequestration = 1.337,
        )
        """

    def testPostFeedlot200ResponseIntermediateInnerIntensities(self):
        """Test PostFeedlot200ResponseIntermediateInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
