# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_intermediate_broilers_inner import PostPoultry200ResponseIntermediateBroilersInner

class TestPostPoultry200ResponseIntermediateBroilersInner(unittest.TestCase):
    """PostPoultry200ResponseIntermediateBroilersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseIntermediateBroilersInner:
        """Test PostPoultry200ResponseIntermediateBroilersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseIntermediateBroilersInner`
        """
        model = PostPoultry200ResponseIntermediateBroilersInner()
        if include_optional:
            return PostPoultry200ResponseIntermediateBroilersInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    }
            )
        else:
            return PostPoultry200ResponseIntermediateBroilersInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    },
        )
        """

    def testPostPoultry200ResponseIntermediateBroilersInner(self):
        """Test PostPoultry200ResponseIntermediateBroilersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
