# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_scope1 import PostPoultry200ResponseScope1

class TestPostPoultry200ResponseScope1(unittest.TestCase):
    """PostPoultry200ResponseScope1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseScope1:
        """Test PostPoultry200ResponseScope1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseScope1`
        """
        model = PostPoultry200ResponseScope1()
        if include_optional:
            return PostPoultry200ResponseScope1(
                fuel_co2 = 1.337,
                fuel_ch4 = 1.337,
                fuel_n2_o = 1.337,
                manure_management_ch4 = 1.337,
                manure_management_n2_o = 1.337,
                atmospheric_deposition_n2_o = 1.337,
                leaching_and_runoff_n2_o = 1.337,
                total_co2 = 1.337,
                total_ch4 = 1.337,
                total_n2_o = 1.337,
                total = 1.337
            )
        else:
            return PostPoultry200ResponseScope1(
                fuel_co2 = 1.337,
                fuel_ch4 = 1.337,
                fuel_n2_o = 1.337,
                manure_management_ch4 = 1.337,
                manure_management_n2_o = 1.337,
                atmospheric_deposition_n2_o = 1.337,
                leaching_and_runoff_n2_o = 1.337,
                total_co2 = 1.337,
                total_ch4 = 1.337,
                total_n2_o = 1.337,
                total = 1.337,
        )
        """

    def testPostPoultry200ResponseScope1(self):
        """Test PostPoultry200ResponseScope1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
