# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner_seasonal_fertiliser_autumn import PostDairyRequestDairyInnerSeasonalFertiliserAutumn

class TestPostDairyRequestDairyInnerSeasonalFertiliserAutumn(unittest.TestCase):
    """PostDairyRequestDairyInnerSeasonalFertiliserAutumn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInnerSeasonalFertiliserAutumn:
        """Test PostDairyRequestDairyInnerSeasonalFertiliserAutumn
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInnerSeasonalFertiliserAutumn`
        """
        model = PostDairyRequestDairyInnerSeasonalFertiliserAutumn()
        if include_optional:
            return PostDairyRequestDairyInnerSeasonalFertiliserAutumn(
                crops_irrigated = 1.337,
                crops_dryland = 1.337,
                pasture_irrigated = 1.337,
                pasture_dryland = 1.337
            )
        else:
            return PostDairyRequestDairyInnerSeasonalFertiliserAutumn(
                crops_irrigated = 1.337,
                crops_dryland = 1.337,
                pasture_irrigated = 1.337,
                pasture_dryland = 1.337,
        )
        """

    def testPostDairyRequestDairyInnerSeasonalFertiliserAutumn(self):
        """Test PostDairyRequestDairyInnerSeasonalFertiliserAutumn"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
