# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_wildseafisheries200_response_intermediate_inner_intensities import PostWildseafisheries200ResponseIntermediateInnerIntensities

class TestPostWildseafisheries200ResponseIntermediateInnerIntensities(unittest.TestCase):
    """PostWildseafisheries200ResponseIntermediateInnerIntensities unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWildseafisheries200ResponseIntermediateInnerIntensities:
        """Test PostWildseafisheries200ResponseIntermediateInnerIntensities
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWildseafisheries200ResponseIntermediateInnerIntensities`
        """
        model = PostWildseafisheries200ResponseIntermediateInnerIntensities()
        if include_optional:
            return PostWildseafisheries200ResponseIntermediateInnerIntensities(
                intensity_excluding_carbon_offset = 1.337,
                intensity_including_carbon_offset = 1.337,
                total_harvest_weight_tonnes = 1.337
            )
        else:
            return PostWildseafisheries200ResponseIntermediateInnerIntensities(
                intensity_excluding_carbon_offset = 1.337,
                intensity_including_carbon_offset = 1.337,
                total_harvest_weight_tonnes = 1.337,
        )
        """

    def testPostWildseafisheries200ResponseIntermediateInnerIntensities(self):
        """Test PostWildseafisheries200ResponseIntermediateInnerIntensities"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
