# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_horticulture_request_crops_inner_refrigerants_inner import PostHorticultureRequestCropsInnerRefrigerantsInner

class TestPostHorticultureRequestCropsInnerRefrigerantsInner(unittest.TestCase):
    """PostHorticultureRequestCropsInnerRefrigerantsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostHorticultureRequestCropsInnerRefrigerantsInner:
        """Test PostHorticultureRequestCropsInnerRefrigerantsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostHorticultureRequestCropsInnerRefrigerantsInner`
        """
        model = PostHorticultureRequestCropsInnerRefrigerantsInner()
        if include_optional:
            return PostHorticultureRequestCropsInnerRefrigerantsInner(
                refrigerant = 'HFC-23',
                charge_size = 1.337
            )
        else:
            return PostHorticultureRequestCropsInnerRefrigerantsInner(
                refrigerant = 'HFC-23',
                charge_size = 1.337,
        )
        """

    def testPostHorticultureRequestCropsInnerRefrigerantsInner(self):
        """Test PostHorticultureRequestCropsInnerRefrigerantsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
