# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_grains_request import PostGrainsRequest

class TestPostGrainsRequest(unittest.TestCase):
    """PostGrainsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostGrainsRequest:
        """Test PostGrainsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostGrainsRequest`
        """
        model = PostGrainsRequest()
        if include_optional:
            return PostGrainsRequest(
                state = 'nsw',
                crops = [
                    {
                        'key' : null
                        }
                    ],
                electricity_renewable = 0,
                electricity_use = 1.337,
                vegetation = [
                    {
                        'key' : null
                        }
                    ]
            )
        else:
            return PostGrainsRequest(
                state = 'nsw',
                crops = [
                    {
                        'key' : null
                        }
                    ],
                electricity_renewable = 0,
                electricity_use = 1.337,
                vegetation = [
                    {
                        'key' : null
                        }
                    ],
        )
        """

    def testPostGrainsRequest(self):
        """Test PostGrainsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
