# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry_request_broilers_inner_meat_other_purchases import PostPoultryRequestBroilersInnerMeatOtherPurchases

class TestPostPoultryRequestBroilersInnerMeatOtherPurchases(unittest.TestCase):
    """PostPoultryRequestBroilersInnerMeatOtherPurchases unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultryRequestBroilersInnerMeatOtherPurchases:
        """Test PostPoultryRequestBroilersInnerMeatOtherPurchases
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultryRequestBroilersInnerMeatOtherPurchases`
        """
        model = PostPoultryRequestBroilersInnerMeatOtherPurchases()
        if include_optional:
            return PostPoultryRequestBroilersInnerMeatOtherPurchases(
                head = 1.337,
                purchase_weight = 1.337
            )
        else:
            return PostPoultryRequestBroilersInnerMeatOtherPurchases(
                head = 1.337,
                purchase_weight = 1.337,
        )
        """

    def testPostPoultryRequestBroilersInnerMeatOtherPurchases(self):
        """Test PostPoultryRequestBroilersInnerMeatOtherPurchases"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
