# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.gaf_api import GAFApi


class TestGAFApi(unittest.TestCase):
    """GAFApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GAFApi()

    def tearDown(self) -> None:
        pass

    def test_post_aquaculture(self) -> None:
        """Test case for post_aquaculture

        Perform aquaculture calculation
        """
        pass

    def test_post_beef(self) -> None:
        """Test case for post_beef

        Perform beef calculation
        """
        pass

    def test_post_buffalo(self) -> None:
        """Test case for post_buffalo

        Perform buffalo calculation
        """
        pass

    def test_post_cotton(self) -> None:
        """Test case for post_cotton

        Perform cotton calculation
        """
        pass

    def test_post_dairy(self) -> None:
        """Test case for post_dairy

        Perform dairy calculation
        """
        pass

    def test_post_deer(self) -> None:
        """Test case for post_deer

        Perform deer calculation
        """
        pass

    def test_post_feedlot(self) -> None:
        """Test case for post_feedlot

        Perform feedlot calculation
        """
        pass

    def test_post_goat(self) -> None:
        """Test case for post_goat

        Perform goat calculation
        """
        pass

    def test_post_grains(self) -> None:
        """Test case for post_grains

        Perform grains calculation
        """
        pass

    def test_post_horticulture(self) -> None:
        """Test case for post_horticulture

        Perform horticulture calculation
        """
        pass

    def test_post_pork(self) -> None:
        """Test case for post_pork

        Perform pork calculation
        """
        pass

    def test_post_poultry(self) -> None:
        """Test case for post_poultry

        Perform poultry calculation
        """
        pass

    def test_post_processing(self) -> None:
        """Test case for post_processing

        Perform processing calculation
        """
        pass

    def test_post_rice(self) -> None:
        """Test case for post_rice

        Perform rice calculation
        """
        pass

    def test_post_sheep(self) -> None:
        """Test case for post_sheep

        Perform sheep calculation
        """
        pass

    def test_post_sheepbeef(self) -> None:
        """Test case for post_sheepbeef

        Perform sheepbeef calculation
        """
        pass

    def test_post_sugar(self) -> None:
        """Test case for post_sugar

        Perform sugar calculation
        """
        pass

    def test_post_vineyard(self) -> None:
        """Test case for post_vineyard

        Perform vineyard calculation
        """
        pass

    def test_post_wildcatchfishery(self) -> None:
        """Test case for post_wildcatchfishery

        Perform wildcatchfishery calculation
        """
        pass

    def test_post_wildseafisheries(self) -> None:
        """Test case for post_wildseafisheries

        Perform wildseafisheries calculation
        """
        pass


if __name__ == '__main__':
    unittest.main()
