# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_sheepbeef200_response_intermediate_sheep import PostSheepbeef200ResponseIntermediateSheep

class TestPostSheepbeef200ResponseIntermediateSheep(unittest.TestCase):
    """PostSheepbeef200ResponseIntermediateSheep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSheepbeef200ResponseIntermediateSheep:
        """Test PostSheepbeef200ResponseIntermediateSheep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSheepbeef200ResponseIntermediateSheep`
        """
        model = PostSheepbeef200ResponseIntermediateSheep()
        if include_optional:
            return PostSheepbeef200ResponseIntermediateSheep(
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = 1.337,
                net = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    }
            )
        else:
            return PostSheepbeef200ResponseIntermediateSheep(
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = 1.337,
                net = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
        )
        """

    def testPostSheepbeef200ResponseIntermediateSheep(self):
        """Test PostSheepbeef200ResponseIntermediateSheep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
