# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner_areas import PostDairyRequestDairyInnerAreas

class TestPostDairyRequestDairyInnerAreas(unittest.TestCase):
    """PostDairyRequestDairyInnerAreas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInnerAreas:
        """Test PostDairyRequestDairyInnerAreas
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInnerAreas`
        """
        model = PostDairyRequestDairyInnerAreas()
        if include_optional:
            return PostDairyRequestDairyInnerAreas(
                cropped_dryland = 1.337,
                cropped_irrigated = 1.337,
                improved_pasture_dryland = 1.337,
                improved_pasture_irrigated = 1.337
            )
        else:
            return PostDairyRequestDairyInnerAreas(
                cropped_dryland = 1.337,
                cropped_irrigated = 1.337,
                improved_pasture_dryland = 1.337,
                improved_pasture_irrigated = 1.337,
        )
        """

    def testPostDairyRequestDairyInnerAreas(self):
        """Test PostDairyRequestDairyInnerAreas"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
