# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_dairy_request_dairy_inner_manure_management_milking_cows import PostDairyRequestDairyInnerManureManagementMilkingCows

class TestPostDairyRequestDairyInnerManureManagementMilkingCows(unittest.TestCase):
    """PostDairyRequestDairyInnerManureManagementMilkingCows unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDairyRequestDairyInnerManureManagementMilkingCows:
        """Test PostDairyRequestDairyInnerManureManagementMilkingCows
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDairyRequestDairyInnerManureManagementMilkingCows`
        """
        model = PostDairyRequestDairyInnerManureManagementMilkingCows()
        if include_optional:
            return PostDairyRequestDairyInnerManureManagementMilkingCows(
                pasture = 0,
                anaerobic_lagoon = 0,
                sump_and_dispersal = 0,
                drain_to_paddocks = 0,
                soild_storage = 0
            )
        else:
            return PostDairyRequestDairyInnerManureManagementMilkingCows(
                pasture = 0,
                anaerobic_lagoon = 0,
                sump_and_dispersal = 0,
                drain_to_paddocks = 0,
                soild_storage = 0,
        )
        """

    def testPostDairyRequestDairyInnerManureManagementMilkingCows(self):
        """Test PostDairyRequestDairyInnerManureManagementMilkingCows"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
