# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_poultry200_response_intermediate_layers_inner import PostPoultry200ResponseIntermediateLayersInner

class TestPostPoultry200ResponseIntermediateLayersInner(unittest.TestCase):
    """PostPoultry200ResponseIntermediateLayersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPoultry200ResponseIntermediateLayersInner:
        """Test PostPoultry200ResponseIntermediateLayersInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPoultry200ResponseIntermediateLayersInner`
        """
        model = PostPoultry200ResponseIntermediateLayersInner()
        if include_optional:
            return PostPoultry200ResponseIntermediateLayersInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    }
            )
        else:
            return PostPoultry200ResponseIntermediateLayersInner(
                id = '',
                scope1 = {
                    'key' : null
                    },
                scope2 = {
                    'key' : null
                    },
                scope3 = {
                    'key' : null
                    },
                carbon_sequestration = {
                    'key' : null
                    },
                intensities = {
                    'key' : null
                    },
                net = {
                    'key' : null
                    },
        )
        """

    def testPostPoultry200ResponseIntermediateLayersInner(self):
        """Test PostPoultry200ResponseIntermediateLayersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
