# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_wildseafisheries_request_enterprises_inner_custombait_inner import PostWildseafisheriesRequestEnterprisesInnerCustombaitInner

class TestPostWildseafisheriesRequestEnterprisesInnerCustombaitInner(unittest.TestCase):
    """PostWildseafisheriesRequestEnterprisesInnerCustombaitInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWildseafisheriesRequestEnterprisesInnerCustombaitInner:
        """Test PostWildseafisheriesRequestEnterprisesInnerCustombaitInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWildseafisheriesRequestEnterprisesInnerCustombaitInner`
        """
        model = PostWildseafisheriesRequestEnterprisesInnerCustombaitInner()
        if include_optional:
            return PostWildseafisheriesRequestEnterprisesInnerCustombaitInner(
                purchased = 1.337,
                emissions_intensity = 1.337
            )
        else:
            return PostWildseafisheriesRequestEnterprisesInnerCustombaitInner(
                purchased = 1.337,
                emissions_intensity = 1.337,
        )
        """

    def testPostWildseafisheriesRequestEnterprisesInnerCustombaitInner(self):
        """Test PostWildseafisheriesRequestEnterprisesInnerCustombaitInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
