# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_aquaculture200_response_scope2 import PostAquaculture200ResponseScope2

class TestPostAquaculture200ResponseScope2(unittest.TestCase):
    """PostAquaculture200ResponseScope2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAquaculture200ResponseScope2:
        """Test PostAquaculture200ResponseScope2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAquaculture200ResponseScope2`
        """
        model = PostAquaculture200ResponseScope2()
        if include_optional:
            return PostAquaculture200ResponseScope2(
                electricity = 1.337,
                total = 1.337
            )
        else:
            return PostAquaculture200ResponseScope2(
                electricity = 1.337,
                total = 1.337,
        )
        """

    def testPostAquaculture200ResponseScope2(self):
        """Test PostAquaculture200ResponseScope2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
