# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_wildseafisheries200_response_scope3 import PostWildseafisheries200ResponseScope3

class TestPostWildseafisheries200ResponseScope3(unittest.TestCase):
    """PostWildseafisheries200ResponseScope3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWildseafisheries200ResponseScope3:
        """Test PostWildseafisheries200ResponseScope3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWildseafisheries200ResponseScope3`
        """
        model = PostWildseafisheries200ResponseScope3()
        if include_optional:
            return PostWildseafisheries200ResponseScope3(
                electricity = 1.337,
                fuel = 1.337,
                bait = 1.337,
                total = 1.337
            )
        else:
            return PostWildseafisheries200ResponseScope3(
                electricity = 1.337,
                fuel = 1.337,
                bait = 1.337,
                total = 1.337,
        )
        """

    def testPostWildseafisheries200ResponseScope3(self):
        """Test PostWildseafisheries200ResponseScope3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
