# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_deer_request_deers_inner_classes import PostDeerRequestDeersInnerClasses

class TestPostDeerRequestDeersInnerClasses(unittest.TestCase):
    """PostDeerRequestDeersInnerClasses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostDeerRequestDeersInnerClasses:
        """Test PostDeerRequestDeersInnerClasses
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostDeerRequestDeersInnerClasses`
        """
        model = PostDeerRequestDeersInnerClasses()
        if include_optional:
            return PostDeerRequestDeersInnerClasses(
                bucks = {
                    'key' : null
                    },
                trade_bucks = {
                    'key' : null
                    },
                breeding_does = {
                    'key' : null
                    },
                trade_does = {
                    'key' : null
                    },
                other_does = {
                    'key' : null
                    },
                trade_other_does = {
                    'key' : null
                    },
                fawn = {
                    'key' : null
                    },
                trade_fawn = {
                    'key' : null
                    }
            )
        else:
            return PostDeerRequestDeersInnerClasses(
        )
        """

    def testPostDeerRequestDeersInnerClasses(self):
        """Test PostDeerRequestDeersInnerClasses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
