# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_beef_request_burning_inner_burning import PostBeefRequestBurningInnerBurning

class TestPostBeefRequestBurningInnerBurning(unittest.TestCase):
    """PostBeefRequestBurningInnerBurning unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostBeefRequestBurningInnerBurning:
        """Test PostBeefRequestBurningInnerBurning
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostBeefRequestBurningInnerBurning`
        """
        model = PostBeefRequestBurningInnerBurning()
        if include_optional:
            return PostBeefRequestBurningInnerBurning(
                fuel = 'coarse',
                season = 'early dry season',
                patchiness = 'high',
                rainfall_zone = 'low',
                years_since_last_fire = 1.337,
                fire_scar_area = 1.337,
                vegetation = 'Melaleuca woodland'
            )
        else:
            return PostBeefRequestBurningInnerBurning(
                fuel = 'coarse',
                season = 'early dry season',
                patchiness = 'high',
                rainfall_zone = 'low',
                years_since_last_fire = 1.337,
                fire_scar_area = 1.337,
                vegetation = 'Melaleuca woodland',
        )
        """

    def testPostBeefRequestBurningInnerBurning(self):
        """Test PostBeefRequestBurningInnerBurning"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
