# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_pork_request_pork_inner_classes_boars import PostPorkRequestPorkInnerClassesBoars

class TestPostPorkRequestPorkInnerClassesBoars(unittest.TestCase):
    """PostPorkRequestPorkInnerClassesBoars unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostPorkRequestPorkInnerClassesBoars:
        """Test PostPorkRequestPorkInnerClassesBoars
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostPorkRequestPorkInnerClassesBoars`
        """
        model = PostPorkRequestPorkInnerClassesBoars()
        if include_optional:
            return PostPorkRequestPorkInnerClassesBoars(
                autumn = 1.337,
                winter = 1.337,
                spring = 1.337,
                summer = 1.337,
                head_purchased = 1.337,
                purchased_weight = 1.337,
                head_sold = 1.337,
                sale_weight = 1.337,
                purchases = [
                    {
                        'key' : null
                        }
                    ],
                manure = {
                    'key' : null
                    }
            )
        else:
            return PostPorkRequestPorkInnerClassesBoars(
                autumn = 1.337,
                winter = 1.337,
                spring = 1.337,
                summer = 1.337,
                head_sold = 1.337,
                sale_weight = 1.337,
                manure = {
                    'key' : null
                    },
        )
        """

    def testPostPorkRequestPorkInnerClassesBoars(self):
        """Test PostPorkRequestPorkInnerClassesBoars"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
