# coding: utf-8

"""
    AIA Calculator API

    Emissions Calculators for various farming activities

    The version of the OpenAPI document: 3.0.0
    Contact: contact@aginnovationaustralia.com.au
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.post_aquaculture_request_enterprises_inner_inbound_freight_inner import PostAquacultureRequestEnterprisesInnerInboundFreightInner

class TestPostAquacultureRequestEnterprisesInnerInboundFreightInner(unittest.TestCase):
    """PostAquacultureRequestEnterprisesInnerInboundFreightInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAquacultureRequestEnterprisesInnerInboundFreightInner:
        """Test PostAquacultureRequestEnterprisesInnerInboundFreightInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAquacultureRequestEnterprisesInnerInboundFreightInner`
        """
        model = PostAquacultureRequestEnterprisesInnerInboundFreightInner()
        if include_optional:
            return PostAquacultureRequestEnterprisesInnerInboundFreightInner(
                type = 'Truck',
                total_km_tonnes = 1.337
            )
        else:
            return PostAquacultureRequestEnterprisesInnerInboundFreightInner(
                type = 'Truck',
                total_km_tonnes = 1.337,
        )
        """

    def testPostAquacultureRequestEnterprisesInnerInboundFreightInner(self):
        """Test PostAquacultureRequestEnterprisesInnerInboundFreightInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
