<?php
/**
 * GAFApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * GAFApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class GAFApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for postAquaculture
     *
     * Perform aquaculture calculation.
     *
     */
    public function testPostAquaculture()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBeef
     *
     * Perform beef calculation.
     *
     */
    public function testPostBeef()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postBuffalo
     *
     * Perform buffalo calculation.
     *
     */
    public function testPostBuffalo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postCotton
     *
     * Perform cotton calculation.
     *
     */
    public function testPostCotton()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postDairy
     *
     * Perform dairy calculation.
     *
     */
    public function testPostDairy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postDeer
     *
     * Perform deer calculation.
     *
     */
    public function testPostDeer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postFeedlot
     *
     * Perform feedlot calculation.
     *
     */
    public function testPostFeedlot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postGoat
     *
     * Perform goat calculation.
     *
     */
    public function testPostGoat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postGrains
     *
     * Perform grains calculation.
     *
     */
    public function testPostGrains()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postHorticulture
     *
     * Perform horticulture calculation.
     *
     */
    public function testPostHorticulture()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPork
     *
     * Perform pork calculation.
     *
     */
    public function testPostPork()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postPoultry
     *
     * Perform poultry calculation.
     *
     */
    public function testPostPoultry()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProcessing
     *
     * Perform processing calculation.
     *
     */
    public function testPostProcessing()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postRice
     *
     * Perform rice calculation.
     *
     */
    public function testPostRice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSheep
     *
     * Perform sheep calculation.
     *
     */
    public function testPostSheep()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSheepbeef
     *
     * Perform sheepbeef calculation.
     *
     */
    public function testPostSheepbeef()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postSugar
     *
     * Perform sugar calculation.
     *
     */
    public function testPostSugar()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postVineyard
     *
     * Perform vineyard calculation.
     *
     */
    public function testPostVineyard()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postWildcatchfishery
     *
     * Perform wildcatchfishery calculation.
     *
     */
    public function testPostWildcatchfishery()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postWildseafisheries
     *
     * Perform wildseafisheries calculation.
     *
     */
    public function testPostWildseafisheries()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
