<?php
/**
 * PostBeefRequestBeefInnerClassesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostBeefRequestBeefInnerClassesTest Class Doc Comment
 *
 * @category    Class
 * @description Beef classes of different types and age ranges
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostBeefRequestBeefInnerClassesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostBeefRequestBeefInnerClasses"
     */
    public function testPostBeefRequestBeefInnerClasses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bulls_gt1"
     */
    public function testPropertyBullsGt1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bulls_gt1_traded"
     */
    public function testPropertyBullsGt1Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers_lt1"
     */
    public function testPropertySteersLt1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers_lt1_traded"
     */
    public function testPropertySteersLt1Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers1_to2"
     */
    public function testPropertySteers1To2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers1_to2_traded"
     */
    public function testPropertySteers1To2Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers_gt2"
     */
    public function testPropertySteersGt2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "steers_gt2_traded"
     */
    public function testPropertySteersGt2Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cows_gt2"
     */
    public function testPropertyCowsGt2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cows_gt2_traded"
     */
    public function testPropertyCowsGt2Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers_lt1"
     */
    public function testPropertyHeifersLt1()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers_lt1_traded"
     */
    public function testPropertyHeifersLt1Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers1_to2"
     */
    public function testPropertyHeifers1To2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers1_to2_traded"
     */
    public function testPropertyHeifers1To2Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers_gt2"
     */
    public function testPropertyHeifersGt2()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "heifers_gt2_traded"
     */
    public function testPropertyHeifersGt2Traded()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
