<?php
/**
 * PostPoultry200ResponseIntermediateLayersInnerIntensitiesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostPoultry200ResponseIntermediateLayersInnerIntensitiesTest Class Doc Comment
 *
 * @category    Class
 * @description PostPoultry200ResponseIntermediateLayersInnerIntensities
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostPoultry200ResponseIntermediateLayersInnerIntensitiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostPoultry200ResponseIntermediateLayersInnerIntensities"
     */
    public function testPostPoultry200ResponseIntermediateLayersInnerIntensities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "poultry_eggs_including_sequestration"
     */
    public function testPropertyPoultryEggsIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "poultry_eggs_excluding_sequestration"
     */
    public function testPropertyPoultryEggsExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eggs_produced_kg"
     */
    public function testPropertyEggsProducedKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
