<?php
/**
 * PostSheepbeef200ResponseIntensitiesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostSheepbeef200ResponseIntensitiesTest Class Doc Comment
 *
 * @category    Class
 * @description PostSheepbeef200ResponseIntensities
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostSheepbeef200ResponseIntensitiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostSheepbeef200ResponseIntensities"
     */
    public function testPostSheepbeef200ResponseIntensities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beef_including_sequestration"
     */
    public function testPropertyBeefIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "beef_excluding_sequestration"
     */
    public function testPropertyBeefExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liveweight_beef_produced_kg"
     */
    public function testPropertyLiveweightBeefProducedKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wool_including_sequestration"
     */
    public function testPropertyWoolIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wool_excluding_sequestration"
     */
    public function testPropertyWoolExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheep_meat_breeding_including_sequestration"
     */
    public function testPropertySheepMeatBreedingIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheep_meat_breeding_excluding_sequestration"
     */
    public function testPropertySheepMeatBreedingExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wool_produced_kg"
     */
    public function testPropertyWoolProducedKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheep_meat_produced_kg"
     */
    public function testPropertySheepMeatProducedKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
