<?php
/**
 * PostSheepRequestSheepInnerClassesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostSheepRequestSheepInnerClassesTest Class Doc Comment
 *
 * @category    Class
 * @description PostSheepRequestSheepInnerClasses
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostSheepRequestSheepInnerClassesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostSheepRequestSheepInnerClasses"
     */
    public function testPostSheepRequestSheepInnerClasses()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rams"
     */
    public function testPropertyRams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_rams"
     */
    public function testPropertyTradeRams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wethers"
     */
    public function testPropertyWethers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_wethers"
     */
    public function testPropertyTradeWethers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "maiden_breeding_ewes"
     */
    public function testPropertyMaidenBreedingEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_maiden_breeding_ewes"
     */
    public function testPropertyTradeMaidenBreedingEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "breeding_ewes"
     */
    public function testPropertyBreedingEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_breeding_ewes"
     */
    public function testPropertyTradeBreedingEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_ewes"
     */
    public function testPropertyOtherEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_other_ewes"
     */
    public function testPropertyTradeOtherEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ewe_lambs"
     */
    public function testPropertyEweLambs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_ewe_lambs"
     */
    public function testPropertyTradeEweLambs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wether_lambs"
     */
    public function testPropertyWetherLambs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_wether_lambs"
     */
    public function testPropertyTradeWetherLambs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_ewes"
     */
    public function testPropertyTradeEwes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trade_lambs_and_hoggets"
     */
    public function testPropertyTradeLambsAndHoggets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
