<?php
/**
 * PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestrationTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestrationTest Class Doc Comment
 *
 * @category    Class
 * @description Horticulture intensities output
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestrationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration"
     */
    public function testPostHorticulture200ResponseIntermediateInnerIntensitiesWithSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "crop_produced_tonnes"
     */
    public function testPropertyCropProducedTonnes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tonnes_crop_excluding_sequestration"
     */
    public function testPropertyTonnesCropExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tonnes_crop_including_sequestration"
     */
    public function testPropertyTonnesCropIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
