<?php
/**
 * PostPoultry200ResponseIntermediateBroilersInnerIntensitiesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostPoultry200ResponseIntermediateBroilersInnerIntensitiesTest Class Doc Comment
 *
 * @category    Class
 * @description PostPoultry200ResponseIntermediateBroilersInnerIntensities
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostPoultry200ResponseIntermediateBroilersInnerIntensitiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostPoultry200ResponseIntermediateBroilersInnerIntensities"
     */
    public function testPostPoultry200ResponseIntermediateBroilersInnerIntensities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "poultry_meat_including_sequestration"
     */
    public function testPropertyPoultryMeatIncludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "poultry_meat_excluding_sequestration"
     */
    public function testPropertyPoultryMeatExcludingSequestration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "meat_produced_kg"
     */
    public function testPropertyMeatProducedKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
