<?php
/**
 * PostWildcatchfishery200ResponseIntensitiesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostWildcatchfishery200ResponseIntensitiesTest Class Doc Comment
 *
 * @category    Class
 * @description PostWildcatchfishery200ResponseIntensities
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostWildcatchfishery200ResponseIntensitiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostWildcatchfishery200ResponseIntensities"
     */
    public function testPostWildcatchfishery200ResponseIntensities()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_harvest_weight_kg"
     */
    public function testPropertyTotalHarvestWeightKg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wild_catch_fishery_excluding_carbon_offsets"
     */
    public function testPropertyWildCatchFisheryExcludingCarbonOffsets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wild_catch_fishery_including_carbon_offsets"
     */
    public function testPropertyWildCatchFisheryIncludingCarbonOffsets()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
