<?php
/**
 * PostAquacultureRequestEnterprisesInnerFluidWasteInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostAquacultureRequestEnterprisesInnerFluidWasteInnerTest Class Doc Comment
 *
 * @category    Class
 * @description PostAquacultureRequestEnterprisesInnerFluidWasteInner
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostAquacultureRequestEnterprisesInnerFluidWasteInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostAquacultureRequestEnterprisesInnerFluidWasteInner"
     */
    public function testPostAquacultureRequestEnterprisesInnerFluidWasteInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fluid_waste_kl"
     */
    public function testPropertyFluidWasteKl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fluid_waste_treatment_type"
     */
    public function testPropertyFluidWasteTreatmentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_inlet_cod"
     */
    public function testPropertyAverageInletCod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_outlet_cod"
     */
    public function testPropertyAverageOutletCod()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "flared_combusted_fraction"
     */
    public function testPropertyFlaredCombustedFraction()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
