<?php
/**
 * PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowersTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowersTest Class Doc Comment
 *
 * @category    Class
 * @description Broiler class with seasonal data
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers"
     */
    public function testPostPoultryRequestBroilersInnerGroupsInnerMeatChickenGrowers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "birds"
     */
    public function testPropertyBirds()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_stay_length50"
     */
    public function testPropertyAverageStayLength50()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liveweight50"
     */
    public function testPropertyLiveweight50()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "average_stay_length100"
     */
    public function testPropertyAverageStayLength100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "liveweight100"
     */
    public function testPropertyLiveweight100()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dry_matter_intake"
     */
    public function testPropertyDryMatterIntake()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dry_matter_digestibility"
     */
    public function testPropertyDryMatterDigestibility()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "crude_protein"
     */
    public function testPropertyCrudeProtein()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manure_ash"
     */
    public function testPropertyManureAsh()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "nitrogen_retention_rate"
     */
    public function testPropertyNitrogenRetentionRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
