<?php
/**
 * PostDairyRequestDairyInnerManureManagementMilkingCowsTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostDairyRequestDairyInnerManureManagementMilkingCowsTest Class Doc Comment
 *
 * @category    Class
 * @description Manure management for each type, each value is a percentage of all excreta, from 0 to 100
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostDairyRequestDairyInnerManureManagementMilkingCowsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostDairyRequestDairyInnerManureManagementMilkingCows"
     */
    public function testPostDairyRequestDairyInnerManureManagementMilkingCows()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pasture"
     */
    public function testPropertyPasture()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "anaerobic_lagoon"
     */
    public function testPropertyAnaerobicLagoon()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sump_and_dispersal"
     */
    public function testPropertySumpAndDispersal()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "drain_to_paddocks"
     */
    public function testPropertyDrainToPaddocks()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "soild_storage"
     */
    public function testPropertySoildStorage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
