<?php
/**
 * PostPorkRequestPorkInnerClassesSowsManureSpringTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AIA Calculator API
 *
 * Emissions Calculators for various farming activities
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@aginnovationaustralia.com.au
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.16.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostPorkRequestPorkInnerClassesSowsManureSpringTest Class Doc Comment
 *
 * @category    Class
 * @description PostPorkRequestPorkInnerClassesSowsManureSpring
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostPorkRequestPorkInnerClassesSowsManureSpringTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostPorkRequestPorkInnerClassesSowsManureSpring"
     */
    public function testPostPorkRequestPorkInnerClassesSowsManureSpring()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "outdoor_systems"
     */
    public function testPropertyOutdoorSystems()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "covered_anaerobic_pond"
     */
    public function testPropertyCoveredAnaerobicPond()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "uncovered_anaerobic_pond"
     */
    public function testPropertyUncoveredAnaerobicPond()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deep_litter"
     */
    public function testPropertyDeepLitter()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "undefined_system"
     */
    public function testPropertyUndefinedSystem()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
