import alias from '@rollup/plugin-alias';
import commonjs from '@rollup/plugin-commonjs';
import json from '@rollup/plugin-json';
import { nodeResolve } from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import { readFileSync } from 'fs';
import { glob } from 'glob';
import { dirname, resolve } from 'path';
import { defineConfig } from 'rollup';
import copy from 'rollup-plugin-copy';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Read package.json to get version
const packageJson = JSON.parse(readFileSync('./package.json', 'utf8'));

// Get all TypeScript files as input
const inputFiles = glob.sync('src/**/*.ts', { ignore: ['**/*.test.ts', '**/test/**'] });

export default defineConfig([
  // ESM build
  {
    input: inputFiles,
    output: {
      dir: 'dist',
      format: 'es',
      preserveModules: true,
      preserveModulesRoot: 'src',
      entryFileNames: '[name].mjs',
    },
    plugins: [
      alias({
        entries: [
          { find: '@', replacement: resolve(__dirname, 'src') }
        ]
      }),
      json(),
      typescript({
        declaration: true,
        declarationDir: 'dist',
        exclude: ['**/*.test.ts', '**/test/**', '**/*.json'],
        tsconfig: './tsconfig.json',
        rootDir: 'src',
        compilerOptions: {
          baseUrl: '.',
          paths: {
            '@/*': ['src/*']
          }
        }
      }),
      nodeResolve({
        preferBuiltins: true,
      }),
      commonjs(),
      copy({
        flatten: false,
        targets: [
          {
            src: 'src/versions/**/*.md',
            dest: 'dist',
          },
        ],
        verbose: true,
      }),
    ],
    external: (id) => {
      // Don't bundle dependencies, but allow internal imports
      return !id.startsWith('.') && !id.startsWith('/') && !id.startsWith('@/') && !id.startsWith('src/');
    },
  },
  // CommonJS build
  {
    input: inputFiles,
    output: {
      dir: 'dist',
      format: 'cjs',
      preserveModules: true,
      preserveModulesRoot: 'src',
      entryFileNames: '[name].cjs',
      exports: 'auto',
    },
    plugins: [
      alias({
        entries: [
          { find: '@', replacement: resolve(__dirname, 'src') }
        ]
      }),
      json(),
      typescript({
        declaration: false, // Already generated by ESM build
        exclude: ['**/*.test.ts', '**/test/**', '**/*.json'],
        tsconfig: './tsconfig.json',
        
      }),
      nodeResolve({
        preferBuiltins: true,
      }),
      commonjs(),
    ],
    external: (id) => {
      // Don't bundle dependencies, but allow internal imports
      return !id.startsWith('.') && !id.startsWith('/') && !id.startsWith('@/') && !id.startsWith('src/');
    },
  },
]);
