import { SheepComplete } from '@/types/Sheep/sheep.input';
import { SheepClasses } from '@/types/Sheep/sheepclasses.input';

const emptySeason = {
  head: 0,
  liveweight: 0,
  liveweightGain: 0,
};

const emptyClass = {
  summer: emptySeason,
  autumn: emptySeason,
  winter: emptySeason,
  spring: emptySeason,
  headShorn: 0,
  woolShorn: 0,
  cleanWoolYield: 0,
  headPurchased: 0,
  purchasedWeight: 0,
  headSold: 0,
  saleWeight: 0,
};

const classes: SheepClasses = {
  tradeRams: emptyClass,
  tradeMaidenBreedingEwes: emptyClass,
  tradeBreedingEwes: emptyClass,
  tradeOtherEwes: emptyClass,
  tradeEweLambs: emptyClass,
  tradeWetherLambs: emptyClass,
  rams: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  wethers: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  maidenBreedingEwes: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  breedingEwes: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  otherEwes: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  eweLambs: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  wetherLambs: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  tradeLambsAndHoggets: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  tradeWethers: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
  tradeEwes: {
    summer: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    autumn: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    winter: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    spring: {
      head: 100,
      liveweight: 100,
      liveweightGain: 100,
    },
    headShorn: 100,
    woolShorn: 100,
    cleanWoolYield: 65,
    headPurchased: 100,
    purchasedWeight: 100,
    headSold: 20,
    saleWeight: 100,
  },
};

export const sheepTestInput: SheepComplete = {
  classes,
  limestone: 3,
  limestoneFraction: 0.9,
  fertiliser: {
    cropsDryland: 2,
    cropsIrrigated: 5,
    otherDryland: 1,
    otherIrrigated: 4,
    pastureDryland: 10,
    pastureIrrigated: 3,
    singleSuperphosphate: 2,
    otherType: 'Monoammonium phosphate (MAP)',
  },
  diesel: 300,
  petrol: 300,
  lpg: 200,
  mineralSupplementation: {
    drySeasonMixUrea: 0.04,
    drySeasonMix: 0.05,
    mineralBlockUrea: 0.3,
    mineralBlock: 0.1,
    weanerBlockUrea: 0.25,
    weanerBlock: 0.01,
  },
  electricitySource: 'State Grid',
  electricityRenewable: 0.3,
  electricityUse: 1000,
  grainFeed: 10,
  hayFeed: 12,
  herbicide: 200,
  herbicideOther: 150,
  merinoPercent: 80,
  ewesLambing: {
    autumn: 0,
    spring: 0.3,
    summer: 0.7,
    winter: 0,
  },
  seasonalLambing: {
    autumn: 0.5,
    spring: 0.5,
    summer: 0.5,
    winter: 0,
  },
};

export const lambingScenarioInput: SheepComplete = {
  limestone: 0,
  limestoneFraction: 0,
  fertiliser: {
    pastureDryland: 0,
    pastureIrrigated: 0,
    cropsDryland: 0,
    cropsIrrigated: 0,
    singleSuperphosphate: 0,
  },
  classes: {
    tradeRams: emptyClass,
    tradeMaidenBreedingEwes: emptyClass,
    tradeBreedingEwes: emptyClass,
    tradeOtherEwes: emptyClass,
    tradeEweLambs: emptyClass,
    tradeWetherLambs: emptyClass,
    rams: emptyClass,
    wethers: emptyClass,
    otherEwes: emptyClass,
    tradeEwes: emptyClass,
    tradeWethers: emptyClass,
    maidenBreedingEwes: emptyClass,
    breedingEwes: {
      summer: {
        head: 400,
        liveweight: 50.333333333333336,
        liveweightGain: -0.010558488469019174,
      },
      autumn: {
        head: 400,
        liveweight: 52.666666666666664,
        liveweightGain: 0.02222839677688247,
      },
      winter: {
        head: 400,
        liveweight: 54,
        liveweightGain: 0.021681649920676893,
      },
      spring: {
        head: 400,
        liveweight: 52.333333333333336,
        liveweightGain: 0.01092896174863388,
      },
      headSold: 0,
      saleWeight: 0,
      headShorn: 400,
      woolShorn: 4.75,
      cleanWoolYield: 65,
      purchases: [],
    },
    eweLambs: {
      spring: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      summer: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      winter: {
        head: 136.66666666666666,
        liveweight: 9,
        liveweightGain: 0.16261237440507667,
      },
      autumn: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      headShorn: 0,
      woolShorn: 0,
      cleanWoolYield: 0,
      headSold: 20,
      saleWeight: 14,
    },
    wetherLambs: {
      spring: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      summer: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      winter: {
        head: 131.66666666666666,
        liveweight: 9,
        liveweightGain: 0.16261237440507667,
      },
      autumn: {
        head: 0,
        liveweight: 0,
        liveweightGain: 0,
      },
      headShorn: 0,
      woolShorn: 0,
      cleanWoolYield: 0,
      headSold: 50,
      saleWeight: 14,
    },
    tradeLambsAndHoggets: emptyClass,
  },
  diesel: 0,
  petrol: 0,
  lpg: 0,
  mineralSupplementation: {
    mineralBlock: 0,
    mineralBlockUrea: 0,
    weanerBlock: 0,
    weanerBlockUrea: 0,
    drySeasonMix: 0.3,
    drySeasonMixUrea: 0.095,
  },
  electricitySource: 'State Grid',
  electricityRenewable: 0,
  electricityUse: 0,
  grainFeed: 3.5,
  hayFeed: 3.5,
  herbicide: 0,
  herbicideOther: 0,
  merinoPercent: 0,
  ewesLambing: {
    spring: 0,
    summer: 0,
    winter: 0.9,
    autumn: 0,
  },
  seasonalLambing: {
    spring: 0,
    summer: 0,
    winter: 1.6,
    autumn: 0,
  },
};
