import { DairyInput } from '@/types/Dairy/input';
import { veg1, veg2, veg3, veg4 } from './vegetation.data';

export const dairies = {
  dairyBullsGt1: {
    spring: {
      head: 20,
      liveweight: 520,
      liveweightGain: 2,
      crudeProtein: 25,
      dryMatterDigestibility: 76,
    },
    summer: {
      head: 20,
      liveweight: 520,
      liveweightGain: 2,
      crudeProtein: 7,
      dryMatterDigestibility: 70,
    },
    autumn: {
      head: 20,
      liveweight: 520,
      liveweightGain: 2,
      crudeProtein: 10,
      dryMatterDigestibility: 62,
    },
    winter: {
      head: 20,
      liveweight: 520,
      liveweightGain: 1,
      crudeProtein: 21,
      dryMatterDigestibility: 75,
    },
  },
  dairyBullsLt1: {
    spring: {
      head: 100,
      liveweight: 50,
      liveweightGain: 1,
      crudeProtein: 25,
      dryMatterDigestibility: 76,
    },
    summer: {
      head: 70,
      liveweight: 50,
      liveweightGain: 1,
      crudeProtein: 7,
      dryMatterDigestibility: 70,
    },
    autumn: {
      head: 50,
      liveweight: 30,
      liveweightGain: 1,
      crudeProtein: 10,
      dryMatterDigestibility: 62,
    },
    winter: {
      head: 40,
      liveweight: 40,
      liveweightGain: 1,
      crudeProtein: 21,
      dryMatterDigestibility: 75,
    },
  },
  heifersGt1: {
    spring: {
      head: 150,
      liveweight: 200,
      liveweightGain: -10,
      crudeProtein: 25,
      dryMatterDigestibility: 76,
    },
    summer: {
      head: 100,
      liveweight: 205,
      liveweightGain: 10,
      crudeProtein: 7,
      dryMatterDigestibility: 70,
    },
    autumn: {
      head: 100,
      liveweight: 223,
      liveweightGain: 0,
      crudeProtein: 10,
      dryMatterDigestibility: 62,
    },
    winter: {
      head: 120,
      liveweight: 211,
      liveweightGain: -3,
      crudeProtein: 21,
      dryMatterDigestibility: 75,
    },
  },
  heifersLt1: {
    spring: {
      head: 100,
      liveweight: 130,
      liveweightGain: 13,
      crudeProtein: 25,
      dryMatterDigestibility: 76,
    },
    summer: {
      head: 80,
      liveweight: 80,
      liveweightGain: 35,
      crudeProtein: 7,
      dryMatterDigestibility: 70,
    },
    autumn: {
      head: 80,
      liveweight: 89,
      liveweightGain: 5,
      crudeProtein: 10,
      dryMatterDigestibility: 62,
    },
    winter: {
      head: 90,
      liveweight: 100,
      liveweightGain: 7,
      crudeProtein: 21,
      dryMatterDigestibility: 75,
    },
  },
  milkingCows: {
    spring: {
      head: 300,
      liveweight: 490,
      liveweightGain: -10,
      crudeProtein: 25,
      dryMatterDigestibility: 76,
      milkProduction: 29,
    },
    summer: {
      head: 300,
      liveweight: 505,
      liveweightGain: 10,
      crudeProtein: 7,
      dryMatterDigestibility: 70,
      milkProduction: 25,
    },
    autumn: {
      head: 250,
      liveweight: 535,
      liveweightGain: 0,
      crudeProtein: 10,
      dryMatterDigestibility: 62,
      milkProduction: 21,
    },
    winter: {
      head: 350,
      liveweight: 510,
      liveweightGain: -3,
      crudeProtein: 21,
      dryMatterDigestibility: 75,
      milkProduction: 10,
    },
  },
} as const;

export const dairyComplete = {
  classes: dairies,
  areas: {
    croppedDryland: 100,
    croppedIrrigated: 200,
    improvedPastureDryland: 200,
    improvedPastureIrrigated: 36,
  },
  cottonseedFeed: 15,
  grainFeed: 15,
  hayFeed: 15,
  herbicide: 500,
  herbicideOther: 200,
  diesel: 7283,
  petrol: 7485,
  lpg: 5000,
  distanceCattleTransported: 23640,
  truckType: '4 Deck Trailer',
  electricityRenewable: 0.1,
  electricityUse: 5700,
  emissionsAllocationToRedMeatProduction: 0.15,
  limestone: 800,
  limestoneFraction: 0.5,
  manureManagementMilkingCows: {
    pasture: 20,
    anaerobicLagoon: 20,
    drainToPaddocks: 2,
    solidStorage: 60,
    sumpAndDispersal: 20,
  },
  manureManagementOtherDairyCows: {
    pasture: 80,
    anaerobicLagoon: 6,
    sumpAndDispersal: 6,
    drainToPaddocks: 20,
    solidStorage: 6,
  },
  seasonalFertiliser: {
    spring: {
      cropsDryland: 5,
      cropsIrrigated: 2,
      pastureDryland: 3,
      pastureIrrigated: 2,
    },
    summer: {
      cropsDryland: 4,
      cropsIrrigated: 3.6,
      pastureDryland: 12.8,
      pastureIrrigated: 3,
    },
    autumn: {
      cropsDryland: 3,
      cropsIrrigated: 7,
      pastureDryland: 7,
      pastureIrrigated: 4,
    },
    winter: {
      cropsDryland: 2,
      cropsIrrigated: 9.2,
      pastureDryland: 4,
      pastureIrrigated: 5,
    },
  },
  fertiliser: {
    cropsDryland: 1,
    cropsIrrigated: 2,
    pastureDryland: 4,
    pastureIrrigated: 2,
    singleSuperphosphate: 4,
    otherType: 'Diammonium Phosphate (DAP)',
    otherDryland: 2,
    otherIrrigated: 2,
  },
} as const;

export const dairyTestData: DairyInput = {
  rainfallAbove600: false,
  state: 'vic',
  productionSystem: 'Non-irrigated Pasture',
  dairy: [dairyComplete],
  vegetation: [veg1, veg2, veg3, veg4],
};
